### ISSUE TITLE
Count message sending errors per user and disable them on a certain threshold

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#103]
Currently, we have specific users that  might have blocked us or similar, and Signals API answers with a HTTP413. The message is definitly not too long, as those users just have one subscription.

Currently, we try to resend the report every 5 minutes when our cronjob runs. We should count those errors per user, and disable them on a certain threshold, I would suggest after 3 tries.

**Comment by errotu** [comment]
Ist das mit #9978b83 gefixt oder willst du nochmal sauberer ran?
