### ISSUE TITLE
Anzahl der Tage in Inzidenzintervall anzeigen

### ISSUE THREAD

**Issue by mammer42** [eknoes/covidbot#112]
Nach dem beschlossenem Stufenplan der letzten MPK wäre es schön zu sehen seit wie vielen Tagen die abonnierten Kreise eine Inzidenz unter 100/50/35 haben.

**Comment by eknoes** [comment]
Gute Idee, ich versuche das mal Anfang der Woche umzusetzen!

**Comment by eknoes** [comment]
Wie genau stellt ihr euch das im Bericht vor? Ich finde der ist schon relativ voll, und in der Zeile selbst wäre ja kaum noch Platz, man müsste ggf. die Klammer erweitern, bspw. so:


> Städte und Landkreise mit Inzidenz >35:
> • Darmstadt (Kreisfreie Stadt): 46,29 :arrow_upper_right: (1 Neuinfektion, 0 Todesfälle, Inzidenz seit 3 Tagen unter 50)

Das finde ich eher ungünstig. Wie seht ihr das, @errotu @mammer42? Oder nur in den detaillierten Bericht, den man über "/Daten Hannover" bekommt?

**Comment by errotu** [comment]
Nur im detaillierten Bericht, würde ich sagen. Und dann jeweils für die Schwellen 35, 50 und 100. Als Beispiel:

> Die 7-Tage-Inzidenz (Anzahl der Infektionen je 100.000 Einwohner:innen) liegt bei 99,21 ↗️. Die Inzidenz ist damit seit x Tagen unter 100.

**Comment by mammer42** [comment]
Im detaillierten Bericht könnte man alle 3 Werte anzeigen zB so:
120 Tage über 35, 
5 Tage unter 50,
72 Tage unter 100.
<Link zu den geltenden Bestimmungen> [falls möglich]

Im täglichen Bericht fände ich es so wie du es geschrieben hast gut, auch wenn es vielleicht unübersichtlicher wird. Als Anwender*in möchte man glaube ich nicht jeden Tag den detaillierten Bericht für mehrere Orte aufrufen um zu sehen was dort gerade erlaubt ist.

**Comment by errotu** [comment]
Ich glaube, den Mehrwert für eine Übersicht mit allen Tagen würde ich nicht so sehen. Das wird eher unübersichtlich. Da vielen Regeln für eine Inzidenz von 100 aber auch erst greifen, wenn ein Ort mehrere Tag in Folge über 100 ist, würde ich vorschlagen, dass wir zukünftig auch anzeigen, wie lange ein Ort bereits über einer Inzidenz von 100 ist. Was meinst du, @eknoes?

**Comment by errotu** [comment]
Dieser Bericht kam gerade als Feedback rein. Kann es sein, dass etwas an der Zählweise nicht ganz funktioniert?

> Liebe Entwickler*innen, irgendwas stimmt an den Zahlen heute nicht, fiel mir gerade auf.
> Am Beispiel Wiesbaden stand da gestern
> 
> "Wiesbaden (Kreisfreie Stadt): 34,47 ↗
> • Seit 4 Tagen (3 Werktagen) unter 35"
> 
> Heute steht da
> " Wiesbaden (Kreisfreie Stadt): 38,78 ↗
> • Seit 2 Tagen (2 Werktagen) über 35, seit 71 Tagen (60 Werktagen) unter 50"
