### ISSUE TITLE
iMessage

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#113]
https://developer.apple.com/business-chat/

**Comment by Lukas2112** [comment]
That sounds like an interesting planned extension!

**Comment by Ein-Tim** [comment]
@eknoes 

Is there any ETA when we can expect the covidbot on iMessage?

**Comment by eknoes** [comment]
No ETA, does not seem like we are qualified:

> To qualify for a Messages for Business account you must have an asynchronous messaging platform staffed by live agents during business hours. Your business must use an Apple-approved MSP.

**Comment by Ein-Tim** [comment]
Oh, okay. I suggest to close this issue if this won't be implemented (-:
