### ISSUE TITLE
Mastodon-Integration

### ISSUE THREAD

**Issue by Lukas2112** [eknoes/covidbot#120]
It might be interesting for some if there was a Mastodon integration that a person holding a Mastodon instance could then implement in their Mastodon instance.

**Comment by eknoes** [comment]
Unfortunately I am not so active in the Fediverse, but as we also have a Twitter Integration we could essentially provide the same Service on Mastodon: https://twitter.com/D64_Covidbot

**Comment by Lukas2112** [comment]
That sounds basically good. I try to contribute as much as I can.

**Comment by Lukas2112** [comment]
I came across [this post here (external link)](https://dev.to/bitsrfr/getting-started-with-the-mastodon-api-41jj) that might explain how you could program a Mastodon Bot in Python. I'll have a look at the documentation and see what I come up with.

**Comment by eknoes** [comment]
If you want, you can start a PR! Otherwise, I just had a chat with @errotu, we might integrate this today or tomorrow by ourselfs :)

**Comment by Lukas2112** [comment]
Wish you and @errotu  every success. Maybe I can see how it differs and complement you and me. Free software makes it possible! :)

**Comment by eknoes** [comment]
Is now implemented, will appear here: [@D64_Covidbot@chaos.social](https://chaos.social/@D64_Covidbot@chaos.social)
