### ISSUE TITLE
Move vaccination information into its own command area

### ISSUE THREAD

**Issue by Lukas2112** [eknoes/covidbot#125]
I could imagine that, for the sake of clarity, it might be useful to be able to subscribe separately to information on vaccination in the future.

**Comment by eknoes** [comment]
Currently, you can get the whole Vaccination info via `/Impfungen`. We are already planning on improvements of the daily report, one would be to not show the vaccination data all the time, e.g. #123 and #91. I would close that as a duplicate :)
