### ISSUE TITLE
Code base to complement already existing Free/Libre Open Source Software or new Free/Libre Open Source Software.

### ISSUE THREAD

**Issue by Lukas2112** [eknoes/covidbot#126]
Wouldn't the core of the applications programmed here be suitable for adding, for example, the password reset function and the possibility of further change notifications (about new applications, for example)? 

Or an idea that came to me while sifting through the code: code basis for a web-based (Django-based?) cross-posting tool.

**Comment by eknoes** [comment]
We have to solve #117 for that, but that already came to my mind in form of #127 :)

**Comment by Lukas2112** [comment]
All right, so you can stay curious if something web based can be realized with the help of Django. I Think that most of it is just linking the program code you programmed for the services and the web-based view that you could run yourself.
