### ISSUE TITLE
Rückgabe der falschen Daten: Essen --> Hessen

### ISSUE THREAD

**Issue by Seestern** [eknoes/covidbot#132]
Hallo, ich nutze den D64 Covidbot unter Mastodon. Wenn ich dem User @D64_Covidbot@chaos.social den Wert "Essen" (ohne Anführungszeichen) übergebe, erhalte ich als Antwort die Daten zu Hessen - ich möchte aber die Daten für die Stadt Essen, nicht für das Land Hessen.

**Comment by eknoes** [comment]
Das habe ich gestern auch gesehen, ich versuche mal die offensichtlichen Fehler in #131 zu sammeln und heute oder morgen zu beheben! Danke für deine Info :)

**Comment by eknoes** [comment]
Ist behoben und deployed :)
