### ISSUE TITLE
Klarere Darstellung bei RKI Verzug

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#133]
Ab einer gewissen Uhrzeit, bspw. 5 Uhr morgens, sollten wir in Antworten bei Twitter/Mastodon und auch den Messengern klarstellen, dass die Daten noch von gestern sind. Aktuell steht da zwar das Datum drin, aber das ist nicht so offensichtlich finde ich! Wenn es platztechnisch reicht könnte man "Für heute sind leider noch keine Daten verfügbar. Gestern ..." einfügen?

**Comment by Lukas2112** [comment]
That would definitely be a useful feature!

**Comment by eknoes** [comment]
Was denkst du @errotu ?

**Comment by errotu** [comment]
Finde ich gut!
