### ISSUE TITLE
Number of persons infected with the SARS-CoV-2 coronavirus, including those who have already recovered and those who have died from and/or with corona in Germany since the beginning of the pandemic

### ISSUE THREAD

**Issue by Lukas2112** [eknoes/covidbot#134]
I can imagine that it might be useful to supplement the report with daily updates of (I.) the total number of people infected with the SARS-CoV-2 coronavirus since the start of the pandemic, (II.) how many of these are considered to have recovered, and (III.) how many people have died in connection with and/or from COVID-19.

**Comment by eknoes** [comment]
See for Recoverd Persons: #15 
Total numbers are already available in the Messenger via `/daten Deutschland`, we do not want to add more information to the daily report but the opposite as it is currently quite large.

Or do you talk the Twitter/Mastodon bots? I think they are to space-limited for that information.

**Comment by Lukas2112** [comment]
All right, thank you very much for your reply. I thought it could be useful in some circumstances, but now see that it would be too much information.
