### ISSUE TITLE
No Threema Covidbot report received via Threema to date.

### ISSUE THREAD

**Issue by Lukas2112** [eknoes/covidbot#135]
I have not received a report on the Threema Bot at this time.

**Comment by eknoes** [comment]
Will come soon, hopefully: https://twitter.com/D64_Covidbot/status/1371036563711389696

**Comment by Lukas2112** [comment]
Such an info message is not yet implemented in Threema, but I think it will be, right?

**Comment by eknoes** [comment]
We have to write such messages manually, this is also implemented for the messenger platforms and we already did it sometimes.
