### ISSUE TITLE
Fehlerhafter Link in Bericht (Signal, Android)

### ISSUE THREAD

**Issue by 6e6e58c4** [eknoes/covidbot#136]
Der Link zu d-64.org am Ende vom Bericht wird (mindestens) in Signal falsch interpretiert und leitet einen auf `https://d-64.org/).` inkl. `/).` am Ende, was in einem `Fehler 404 – Nicht gefunden` endet.

Stelle im Code: [bot.py, Zeile 371/372](https://github.com/eknoes/covidbot/blob/d1dfe7992d7667fe297af0c85a7e0a7e174a8b29/covidbot/bot.py#L371)
```py
'der Daten zu erhalten. Ein Service von <a href="d-64.org/">D64 - Zentrum für Digitalen ' \
'Fortschritt</a>.</i>'.format(info_command=self.format_command("Info"))
```
![Screenshot_20210314-165524078](https://user-images.githubusercontent.com/35571800/111075145-e4bf0300-84e6-11eb-9451-2f0b1aee2844.jpg)

--
Android: 10
Signal: 5.4.12

**Comment by errotu** [comment]
Vielen Dank für den Hinweis! Ist nun gefixt.
