### ISSUE TITLE
Twitter-Update terminieren

### ISSUE THREAD

**Issue by errotu** [eknoes/covidbot#140]
Derzeit senden wir das Update mit den Infektionszahlen bei Twitter raus, sobald wir die Daten haben (regelmäßig gegen 04 Uhr). Ich glaube, dass es damit bereits bei vielen weit unten auf dem Feed ist, wenn sie zwischen 06 und 08 Uhr das erste Mal auf ihr Handy schauen. Wollen wir den Tweet vielleicht erst gegen 06:30 Uhr abschicken, auch wenn die Zahlen schon vorher haben?

**Comment by eknoes** [comment]
Finde ich gut! Ich fände glaube ich 6 Uhr besser, ab da steigt in der Regel auch die Botinteraktion an!
