### ISSUE TITLE
Impfgeschwindigkeit

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#142]

**Comment by errotu** [comment]
Wollen wir die Impfgeschwindigkeit vielleicht auch in den Tweet-/Trööt-/Instagrampost zu den aktuellen Impfzahlen aufnehmen? Oder wird der dann zu lang?
Zu Visualisierung der aktuellen Geschwindigkeit fände ich eine Grafik [wie diese](https://twitter.com/janoschdahmen/status/1373953181336666113?s=20) schick.
