### ISSUE TITLE
Nutzer:innenumfrage zum Bericht

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#144]
Mein Vorschlag für ne Umfrage, die glaube ich die Dinge abdecken würde die ich gerne wissen will:

### Einleitung
Im Covidbot kann man verschiedene Orte in Deutschland abonnieren und bekommt am Morgen eine Zusammenfassung zur Neuinfektionslage in diesen Orten. Außerdem wird die aktuelle Situation bezüglich Impfungen und Intensivbetten dargestellt und teilweise grafisch aufbereitet. Diesen aktuell täglichen Bericht wollen wir gerne deutlich verbessern.
Eine Idee ist, eine kleine Anzahl von Berichtstypen anzubieten, für die man sich entscheiden kann. Diese sollen sich im Umfang und der Häufigkeit unterscheiden. Eine andere Idee wäre, täglich einen kürzeren Bericht zu versenden welcher ein bis zweimal die Woche einen größeren Umfang an Daten enthält. Was dir dabei am liebsten ist, wollen wir hier gerne schnell und anonym erfahren! 

### Fragen
**Wie häufig würdest du gerne Informationen von unserem Bot erhalten?**
[Täglich, Mehrmals pro Woche, Wöchentlich, Seltener]

**Welche Informationen würdest du gerne regelmäßig erhalten?**
- [ ] Bundesweite Infektionslage
- [ ] Impfsituation
- [ ] Intensivbettenbelegung
- [ ] Kurzen Überblick über Infektionen in abonnierten Orten
- [ ] Detailbericht über Infektionen in abonnierten Orten

**Würdest du dir wünschen, bestimmte Daten weniger häufig zu bekommen?**
- Bundesweite Infektionslage [Weniger Häufig, Nie]
- Impfsituation [Weniger Häufig, Nie]
- Intensivbetten [Weniger Häufig, Nie]
- Regeln [Weniger Häufig, Nie]

**Welche Grafiken würdest du gerne in welcher Regelmäßigkeit erhalten?**
- Bundesweite Neuinfektionen  [Täglich, Mehrmals pro Woche, Wöchentlich, Nie]
- Bundesweite Inzidenz  [Täglich, Mehrmals pro Woche, Wöchentlich, Nie]
- Impfüberblick  [Täglich, Mehrmals pro Woche, Wöchentlich, Nie]
- Inzidenzgrafik für jeden abonnierten Ort  [Täglich, Mehrmals pro Woche, Wöchentlich, Nie]
- Neuinfektionsgrafik für jeden abonnierten Ort  [Täglich, Mehrmals pro Woche, Wöchentlich, Nie]
- Ich möchte Berichte nur in Textform, ohne Grafiken, erhalten

**Verwendest du Befehle, um Detailinformationen, wie Impfdaten, Regeln oder ähnliches, zu bestimmten Themen zu bekommen?**
[Ja, Nein, Kenne ich nicht]

**Gibt es Tage, an dem du gerne einen ausführlicheren Bericht von uns bekommen würdest?**
- [ ] Nein
- [ ] Mo
- [ ] Di
- [ ] ...
- [ ] So

**Ich nutze den Covidbot auf...**
- [ ] Telegram
- [ ] Threema
- [ ] Signal
- [ ] Twitter
- [ ] Mastodon
- [ ] Instagram

**Wie bist du auf den Covidbot aufmerksam geworden?**
- [ ] Über Bekannte
- [ ] Über Twitter
- [ ] Über Instagram
- [ ] Über eine öffentliche Facebook- oder Telegramgruppe
- [ ] Über den D64-Ticker
- [ ] Anders: KURZTEXT

**Das möchte ich euch noch sagen:**
TEXTFELD

**Comment by errotu** [comment]
Vielen Dank für die Initiative! Ich habe ein paar kleine Änderungen vorgenommen und eine Frage ergänzt. Was denkst du?
