### ISSUE TITLE
Facebook (Messenger)

### ISSUE THREAD

**Issue by errotu** [eknoes/covidbot#145]
Nachdem wir nun bereits eine [Facebookseite](https://www.facebook.com/D64Covidbot/) (für das Insta-Profil) haben, könnten wir uns überlegen, ob wir auf der auch jeweils die Insta-Posts veröffentlichen. Über den Messenger könnten wir vielleicht auch die gleichen Interaktionen wie bei Twitter, vielleicht sogar Abonnements ermöglichen (das wir Letzteres nicht haben, wurde [bei Chip.de](https://www.chip.de/downloads/webapp-D64-Covidbot_183302658.html) explizit negativ erwähnt).

**Comment by eknoes** [comment]
Ganz grob jetzt implementiert, läuft aktuell nur manuell. Es gibt Probleme mit der Formatierung, Markdown wird wohl nur im Browser gerendert und sonst nicht - also müssen wir das machen wie bei Signal. Er reagiert relativ langsam, aber das liegt glaube ich an Facebook. Leider haben die Pythonlibraries nicht richtig funktioniert, deshalb gibts jetzt noch ein neues, zusätzliches Sideproject: https://github.com/eknoes/simple-fbmessenger

**Comment by eknoes** [comment]
Wir können nur Nachrichten an Leute versenden, die uns innerhalb der letzten 24h eine Nachricht gesendet haben - außer wir werden eine Nachrichtenorganisation: https://www.facebook.com/help/publisher/316333835842972

**Comment by errotu** [comment]
Wir können den Status als "Nachrichtenseite" nicht beantragen, weil die Seite noch keine 90 Tage alt ist. Also gibt es wohl keine Abofunktion, sondern nur Infos auf Anfrage, oder?

**Comment by eknoes** [comment]
Sollen wir dann auch die Befehle /abo & Co streichen? Dann müssen wir ja echt auch einiges an Funktionalität anpassen :sob:

**Comment by errotu** [comment]
Stimmt, es bringt echt einen Rattenschwanz mit sich. Mir fällt aber leider gerade auch nichts Besseres ein. Könnten wir auf der Facebook-Page selbst noch die Inhalte posten, die wir auch bei Insta- und Twitter veröffentlichen?

**Comment by eknoes** [comment]
Bestimmt, da kann ich mir die API danach mal ansehen!
