### ISSUE TITLE
Calculating how far we are to achieve herd immunity

### ISSUE THREAD

**Issue by Lukas2112** [eknoes/covidbot#146]
Based on the information on how many have received the first and second vaccination and the number of inhabitants in Germany, couldn't we have it calculated how far away we are from herd immunity on a daily basis?

Perhaps this could be attached as a text message, as well as a diagram (especially for social media platforms?), as Quarks from Westdeutscher Rundfunk did [here](https://www.instagram.com/p/CLerJtxqqwT/)?

**Comment by eknoes** [comment]
Ist ja jetzt gewissermaßen drin, nicht Herdenimmunität, aber bis alle geimpft sind. Dadurch, dass kein fester Wert feststeht, würde ich ungern die Herdenimmunität "festlegen".
