### ISSUE TITLE
Formatierung: Tendenz

### ISSUE THREAD

**Issue by errotu** [eknoes/covidbot#148]
Feedback per Mail:

> Kann man die Inzidenz, das Symbol ob gestiegen oder gefallen jeweils in eine neue Zeile machen? Das würde die Nachricht zwar etwas länger machen, aber dafür auch etwas übersichtlicher. Alternativ die Inzidenz und den Pfeil in eine Zeile und den Rest der Daten jeweils in eine eigene Zeile.

Hier bin ich etwas skeptisch, generell bekommen wir eher Feedback, dass der tägliche Bericht schon jetzt etwas lang ist.

**Comment by eknoes** [comment]
Können wir ja mal im Hinterkopf behalten, wir wollen den Bericht ja eh verändern. Das geschieht dann in #122
