### ISSUE TITLE
Sortierung der Orte im Bericht

### ISSUE THREAD

**Issue by errotu** [eknoes/covidbot#149]
Feedback per Mail:

> Ich habe gerade 3 Landkreise aboniert. Heute morgen erschien die Statistik. Kann man die vielleicht aufsteigend und nicht absteigend sortieren? Also die Gruppierungen der Orte.

Das individuell zu gestalten ist recht aufwändig. Im Allgemeinen würde ich eher die aktuelle Sortierung beibehalten, weil hierdurch die Orte mit hoher Inzidenz, bei denen also auch eine höhere "Alarmbereitschaft" gegeben sein muss, direkter ins Auge fallen.

**Comment by eknoes** [comment]
Sehe ich ähnlich wie du!
