### ISSUE TITLE
Informationen über Genese

### ISSUE THREAD

**Issue by errotu** [eknoes/covidbot#15]
Wäre eine hilfreiche Angabe, leider scheint die entsprechende Spalte vom RKI nicht gepflegt zu werden. Vielleicht Kontakt mit dem RKI aufnehmen, warum das der Fall ist?

[Ob statistisch alle als genesen erfasst werden, die seit 14 Tagen nicht gemeldet wurden](https://github.com/eknoes/covid-bot/issues/9#issuecomment-752190565), bin ich ziemlich skeptisch. Zum einen sind noch die Todesfälle zu berücksichtigen, zum anderen würden schwerere Krankheitsverläufe, die über 14 Tage andauern, dann gar nicht (mehr) erfasst werden.

**Comment by errotu** [comment]
[Es scheint tatsächlich so zu sein](https://www.riffreporter.de/corona-virus/faq-genesene-statistik-rki/), dass man nach der Statistik des RKI 14 Tage nach Meldung der Infektion "genesen" ist, unabhängig vom tatsächlichen, individuellen Krankheitsverlauf.

**Comment by errotu** [comment]
Wollen wir das noch aufnehmen? Oder einfach sein lassen, weil es im Grunde wenig aussagekräftig ist, @eknoes?

**Comment by eknoes** [comment]
Ich würde es dann einfach sein lassen, ich denke es ist kaum aussagekräfitg, und wir haben schon mehr als genug Daten!
