### ISSUE TITLE
Grafik mit Graphen von mehreren Orten

### ISSUE THREAD

**Issue by errotu** [eknoes/covidbot#150]
Feedback per Mail:

> Besteht die Möglichkeit, dass man die Grafik der abonnierten Orte in mehreren Farben in ein Koordinatensystem aufträgt? Hier ist es vielleicht sinnvoll eine maximale Anzahl festzulegen und dann wieder nur Deutschland komplett anzuzeigen.

Gute Idee! Ist aktuell auch schon in Planung!

**Comment by eknoes** [comment]
Top, dann haben wir auch endlich einen Issue dazu. Wenn ich das baue, können wir ja mal schauen ab welcher Anzahl von Orten es unübersichtlich wird! Anstatt nut verschiedene Farben zu nehmen würde ich auch unterschiedliche Linien implementieren: [hier](https://matplotlib.org/stable/gallery/lines_bars_and_markers/linestyles.html) sind die möglichen Varianten!

**Comment by eknoes** [comment]
Das wäre mein erster Entwurf:

![Graph with several incidence values](https://dl.eknoes.de/graph.jpg)

**Comment by eknoes** [comment]
Ich finde es noch eher unübersichtlich, vielleicht wäre es statt Legende sinnvoll, am "Ende" einer Linie den Namen hinzuschreiben!

**Comment by errotu** [comment]
Ich bin mir nicht sicher, wie gut das klappt, wenn mehrere Linien am Ende nah beieinander sind. Kann man die Orte in der Legende vielleicht in der Reihenfolge sortieren, in der die Graphen beginnen oder aufhören?
Für die Farbgebung könnte das [Color Wheel von Adobe](https://color.adobe.com/de/create/color-wheel) mit der Einstellung "Triade" hilfreich sein.

**Comment by eknoes** [comment]
Meinst du mit Beginnen oder aufhören die erste / letzte Inzidenz?

Das wäre jetzt ein passender Farbvorschlag:
![A](https://dl.eknoes.de/graph2.jpg)

**Comment by errotu** [comment]
Ja, genau, das meinte ich. Der aktuelle Vorschlag gefällt mir gut!

**Comment by eknoes** [comment]
Können wir machen, oder einfach die 5 zu erst abonnierten Orte?

**Comment by errotu** [comment]
Wir haben ja jetzt eine schöne Grafik, aber wann soll die eigentlich genau ausgespielt werden? Als zweite Grafik mit dem täglichen Bericht?

**Comment by brezelman** [comment]
> Ich wäre für die fünf letzten abonnierten Orte. Dann lässt sich die Graphenanzeige leichter manipulieren.

Das führt nur leider dazu, dass bei den meisten Leuten wohl der ihnen wichtigste, zuerst hinzugefügte, Ort fehlt. Die Entscheidung würde ich noch einmal überdenken.

**Comment by eknoes** [comment]
Das ist ein guter Punkt, das stimmt. Was denkst du dazu, @errotu? Andererseits hat man dann auch am ehesten noch den Einfluss darauf, was angezeigt wird.

**Comment by eknoes** [comment]
Hier mal ein kurzer Überblick über die Anzahl der Abos:

| Anzahl Abos | Anzahl Nutzer:innen|
|-----|------|
| 1   | 526  |
| 2   | 1836 |
| 3   | 1062 |
| 4   | 488  |
| 5   | 308  |
| 6   | 133  |
| 7   | 91   |
| 8   | 50   |
| 9   | 24   |
| 10  | 7    |
| 11  | 4    |
| 12  | 2    |
| 13  | 3    |
| 16  | 1    |
| 17  | 3    |
| 19  | 1    |
| 22  | 1    |
| 28  | 1    |
| 32  | 1    |
| 34  | 1    |
| 35  | 1    |
| 74  | 1    |
| 101 | 1    |

**Comment by eknoes** [comment]
Es ist also nur für vergleichsweise wenig Nutzer:innen relevant und wenn es für dich wichtig genug ist hier einen Issue zu suchen und zu kommentieren, dann sollten wir es vielleicht anpassen?

**Comment by brezelman** [comment]
> Es ist also nur für vergleichsweise wenig Nutzer:innen relevant und wenn es für dich wichtig genug ist hier einen Issue zu suchen und zu kommentieren, dann sollten wir es vielleicht anpassen?
Mir wäre geholfen, wenn statt den letzten die ersten fünf Orte erscheinen würden. Aber ob andere User das genauso sehen? Es gibt ja einen Grund, warum Leute mehr als fünf Orte abonnieren. Dieser ist wohl meist, dass sie sich eben für mehr als fünf Orte interessieren. Da welche wegzulassen wird also voraussichtlich immer jemanden nicht zufriedenstellen.
Könnt ihr eventuell einen zweiten Graphen erzeugen und senden für die nächsten bis zu fünf Orte? Dann wären für fast jeden Benutzer alle seine Orte abgedeckt.

**Comment by eknoes** [comment]
> Könnt ihr eventuell einen zweiten Graphen erzeugen und senden für die nächsten bis zu fünf Orte? Dann wären für fast jeden Benutzer alle seine Orte abgedeckt.

Finde ich eine interessante Lösung. Oder wir ehöhen das Limit einfach, auch wenn es dann übersichtlicher wird? Ich glaube, dass wir so richtig viele Grafiken versenden würde ich ungern machen, bevor der Bericht nicht konfigurierbar ist. Für dich wäre ja auch ein Workaround, die Orte die du am Anfang abonniert hast und dir wichtig sind zu de-abonnieren und wieder neu zu abonnieren!

**Comment by errotu** [comment]
Mein Eindruck ist nach wie vor, dass die letzten Orte (und nicht die ersten) den Vorteil haben, dass man sie über deabonnieren und neu abonnieren deutlich leichter konfigurieren können.
Das Limit anheben macht auch Sinn, denke ich. Wenn wir bspw. 7 oder 8 Graphen zulassen, bekommen 95% aller Nutzer:innen sämtliche Orte, halbwegs übersichtlich dürfte es aber trotzdem noch sein.

**Comment by eknoes** [comment]
Ist jetzt deployed, ab morgen werden bis zu 8 Städte in einer Grafik gezeigt. Testen kann man bspw. mit `/bericht`
