### ISSUE TITLE
signald Upgrade

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#153]
New release is available, maybe it also improves stability

**Comment by eknoes** [comment]
We can't use the current signald version, as we have a problem with gradle / Java, so we have to wait for Gradle 7 to be released.

**Comment by jennydiss** [comment]
Bitte entfernen Sie mich aus dem Verteiler. Mit freundlichen Grüßen Claudia Disselhoff Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Sönke ***@***.***> Datum: 03.12.21  12:23  (GMT+01:00) An: eknoes/covidbot ***@***.***> Cc: Subscribed ***@***.***> Betreff: Re: [eknoes/covidbot] signald Upgrade (#153) 
Closed #153.
