### ISSUE TITLE
Benachrichtigung der Abos klappt nicht bei Threema

### ISSUE THREAD

**Issue by budda85** [eknoes/covidbot#154]
Ich habe bei mir in Threema zwei Orte abonniert, welche mir auch mit dem Befehl "Abo", angezeigt werden.
Wenn ich morgens mein Smartphone anschalte, bekomme ich allerdings nur die Deutschlandweite Grafik der Neuinfektionen und den Coronabericht vom aktuellen Tag zugeschickt.
Eine manuelle Abfrage der Orte klappt allerdings wunderbar.
Threema nutze ich ohne Google-Play-Dienste und nur mit dem polling, was meiner Meinung nach kein Problem sein sollte, da der Coronabericht ankommt. Ein beenden und neues abonnieren der Orte brachte auch keinen Erfolg.
Was mache ich falsch?

**Comment by errotu** [comment]
Gar nichts! Der tägliche Bericht zeigt in der Grafik derzeit nur die deutschlandweiten Zahlen an, keine Informationen zu den einzelnen Abonnements (zu denen gibt es nur im Text des Berichts Zahlen). Wir arbeiten aber daran, das zu verbessern, siehe #150.

**Comment by budda85** [comment]
Achso, sorry. Dann hatte ich das falsch verstanden. Ich dachte ich bekomme immer die kompletten Grafiken und Info-Daten von meinen abonnierten Orten geschickt, wie wenn ich "Daten ORT" schicke.
Danke
