### ISSUE TITLE
Impftempo in Tweet

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#158]
Sollten wir vllt. auch das noch in den Impftweet mitaufnehmen? Scheint irgendwie relevant zu sein, gemeinsam mit #157

**Comment by errotu** [comment]
Meinst du in den Text, nicht nur in die Grafik? Oder was ist der Unterschied zu #157?

**Comment by eknoes** [comment]
Genau

**Comment by eknoes** [comment]
Wir könnten ja auch nen Thread machen, und dann auch so einen Impfbalken darunter mit dem Fortschritt!

**Comment by errotu** [comment]
Ja, das wäre cool!
