### ISSUE TITLE
Aktuell geltende Verordnungen integrieren

### ISSUE THREAD

**Issue by errotu** [eknoes/covidbot#16]
Viele Kommunen veröffentlichen ihre Corona-Beschränkungen über das Katastrophenwarnsystem des Bundes (wird dann bspw. über NINA angezeigt). Vielleicht kann man das System anzapfen, so dass für die abonnierten Orte auch diese Meldungen angezeigt werden.

Eine offizielle API [gibt es leider nicht](https://fragdenstaat.de/anfrage/dokumentation-der-mowas-api/#nachricht-512349), [aber diese JSON-Datei](https://warnung.bund.de/bbk.mowas/gefahrendurchsagen.json) ([Hintergrund](https://fragdenstaat.de/anfrage/dokumentation-der-mowas-api/#nachricht-512805)). Die Meldungen selbst sind auch nicht urheberrechtlich geschützt ([§ 5 UrhG](https://dejure.org/gesetze/UrhG/5.html)), die Datenbank als solche könnte aber Schutz genießen (dann dürften wir nicht ohne Erlaubnis drauf zugreifen). Wir könnten die Rechtsauffassung des Bundesamts für Bevölkerungsschutz und Katastrophenhilfe (BBK) anfragen, ggf. könnte man auch FragDenStaat bzw. die OpenKnowledgeFoundation um Unterstützung in der Angelegenheit bitten.

**Comment by eknoes** [comment]
Diese API können wir nutzen: https://tourismus-wegweiser.de/connect/

In Verbindung mit #112 kann das echt nützlich sein! :)

**Comment by errotu** [comment]
Ich würde folgende Umsetzung vorschlagen:
In dem Bericht eines bestimmten Ortes zeigen wir immer die Ampelfarbe für das jeweilige Bundesland an. Die ergibt sich aus dem (gerundeten) Schnitt aller einzelnen Ampelwerte für das Bundesland. Außerdem der Hinweis:

> Wenn du weitere Informationen zu den Beschränkungen in [Bundesland] erhalten möchtest, schicke uns einfach die Nachricht "Regeln [Bundesland]"

"Regeln [Bundesland]" löst dann einen Bericht aus, in dem alle betroffenen Bereiche mit Ampelsymbol aufgelistet werden. Wenn sich die Ampelsymbole für "Öffnung und Zugang" sowie "Aufenthalt und Hygiene" unterscheiden, zeigen wird beides an. Am Fuß der Nachricht steht:

> Detailliertere Informationen zu den Beschränkungen findest du auf [Link zur tourismus-wegweiser.de-Seite des Bundeslandes] 

Wenn man nur "Regeln" schickt, erhält man separate Nachrichten für all die Bundesländer, von denen man Städte (oder das Bundesland selbst) abonniert hat. Jeweils mit dem Inhalt, der auch bei "Regeln [Bundesland]" ausgegeben wird.

**Comment by eknoes** [comment]
Ich wollte gerade anfangen das zu implementieren und frage mich, wie sinnvoll das überhaupt ist, mehr als einen Link zu den Regeln des jeweiligen Bundeslandes zu implementieren. Mit den Ampeln kann man am Ende auch nicht mehr sehen, als was man im Alltag eh mitbekommt, oder? Also dass bspw. ein Geschäft wieder aufmacht. Was würdest du dazu denken, einfach nur den Link zu den Regeln in den Bericht zu einem Ort aufzunehmen? Deren JSON File ist auch nicht so das wahre vom Ei. Auf jeden Fall würde ich die Prio erstmal niedrieger setzen, ich denke Intensivbetten o.Ä. sind erstmal sinnvoller als diese Ampelflut! Was denkst du?

**Comment by errotu** [comment]
Hm, ganz valide Punkte. Trotzdem scheint mir eine unmittelbare Anzeige der Regeln ein recht viel nachgefragtes Feature zu sein. Was hältst du davon, wenn "Regeln [Bundesland]" den Text zum Feld "Kontaktbeschränkungen" ausgibt? Das scheint mir das Relevanteste zu sein. Für den Rest dann der Link zur Webseite.

**Comment by eknoes** [comment]
Mit 2617dc06 implementiert.

**Comment by errotu** [comment]
Ich würde vorschlagen, dass wir einen Befehl einführen, der nur die Kontaktbeschränkungen ausgibt ("Regeln xxx"). Ich glaube, dass die Funktion wirklich für viele interessant ist und deshalb prominenter in der Benutzerführung erscheinen sollte. Meine Vorstellung wäre, dass wir eine dritte Option "Regeln in BUNDESLAND" neben Daten und Abo haben, wenn jemand uns einen Ortsnamen schickt.

**Comment by eknoes** [comment]
Finde ich gut

**Comment by eknoes** [comment]
Ist jetzt implementiert und online.
