### ISSUE TITLE
Grafik für Intensivregisterdaten 

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#160]
Finde diese Grafik über Zeit gut, vllt. mit neuem Befehl `/intensivbetten` oder so?

Rechts neben der Karte, `Intensivbetten­belegung im Zeitverlauf`:
https://www.zeit.de/wissen/2020-04/coronavirus-intensivbetten-deutschland-auslastung-kapazitaeten-tagesaktuelle-karte

**Comment by errotu** [comment]
Ja, finde ich auch schick. Dann seit dem Ausbruch der Pandemie? Ich fände insgesamt einen Befehl gut, der einem alle Graphen (Inzidenz, Infektionen, Intensivbetten) seit dem Ausbruch der Pandemie zeichnet. Vielleicht "Historie"? Auf Wunsch auch anpassbar mit Ortsnamen?

**Comment by eknoes** [comment]
Bei den Intensivbetten und den Impfungen ist das kaum ein Problem, für die Inzidenzen müssten wir noch massiv viele Daten aggregieren, ist aber möglich. Finde ich einen coolen Vorschlag und auf jeden Fall sinnvoll!

**Comment by eknoes** [comment]
Alle Daten: https://www.divi.de/divi-intensivregister-tagesreport-archiv-csv?start=0&limit=500
