### ISSUE TITLE
Signal bot nicht ansprechbar => FAQ

### ISSUE THREAD

**Issue by cjue** [eknoes/covidbot#165]
Es kam jetzt schon mehrmals vor, dass der Signal Bot nicht auf Nachrichten reagiert, es wird nicht mal eine Empfangsbestätigung für die Eingabe angezeigt.

Falls das mit dem Rate-Limiting #100 zusammenhängt: Könntet ihr das noch auf der Webseite ergänzen, dass nicht nur ausfallende Updates sondern auch ausbleibende Antworten durch temporäres Throttling o.Ä. verursacht werden? 

Würde die Fehlersuche bei einigen verkürzen.

**Comment by eknoes** [comment]
Danke für den Issue! Es scheint gerade öfter zu Fehlern beim Signalbot zu geben, so richtig einordnen können wir das aktuell selbst nicht. Ich versuche mich mal mehr auf die Suche zu geben und hoffe was zu finden.

**Comment by cjue** [comment]
Interessanterweise wurde heute die Antwort dann nach 40 Minuten nachgeliefert, während es bisher immer entweder sofort oder gar nicht funktioniert hatte.

**Comment by eknoes** [comment]
Ja, das liegt ein bisschen daran wo der Fehler vor dem von uns getriggerten Neustart lag - wir benutzen für Signal nicht nur unseren Bot, sondern der kommuniziert über einen Socket mit [signald](https://gitlab.com/signald/signald). Und je nachdem, ob der denkt unserem Bot die Nachrichten schon zugestellt bekommen zu haben bekommst du nach dem Neustart eine Nachricht oder nicht. Ich muss mich die Tage nochmal richtig hinsetzen und diese "Crashes" analysieren, wir haben jetzt für ein paar Tage Debuglogs und ich denke da sollten wir was finden, was uns zu den Fehlern führt :)

**Comment by eknoes** [comment]
Ich habe heute einen Fehler gefunden, bei dem ich vermute, dass es mit diesem zusammenhängt. Das ist jetzt so deployed, wir müssen mal weiter beobachten, ob da was passiert: 45e8bce7200e1454fa43713940671f1a9c0f8953

**Comment by eknoes** [comment]
Läuft jetzt wieder stabil seit einiger Weile!
