### ISSUE TITLE
"In X Städten sind nur noch weniger als Y% der Betten frei"

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#166]
> Könnt ihr automatisch auswerten, wieviele Kliniken weniger als ein/zwei Betten frei habe und/oder wie viele am Maximum oder sehr kurz davor sind?
https://twitter.com/SebStange/status/1382653039484489734

**Comment by errotu** [comment]
Fände ich gut. Vielleicht:

> In x Städten sind 90% oder mehr der Betten belegt, y Städte haben  keine freien Intensivbetten mehr.
