### ISSUE TITLE
Abo NRW startet Abo für Dortmund

### ISSUE THREAD

**Issue by sebastianbrinkmann76** [eknoes/covidbot#168]
Ich wollte gerade die Zahlen für NRW abonnieren, aber der bot auf Threema schickt mir stattdessen Dortmund.

**Comment by eknoes** [comment]
Danke fürs melden! Ich denke, um das schön zu lösen müssten wir wirklich #88 einführen.

Zum Verständnis, warum das passiert: NRW kann der Bot nicht zuordnen, weil wir eben nur die ausgeschriebene Variante der Bundesländer selbst in der Datenbank haben. Dann durchsuchen wir OpenStreetMap, das liefert uns einen Punkt in NRW zurück (anscheinend mitten in Dortmund), und wir gehen dann von Dortmund aus.
