### ISSUE TITLE
Trend wird bei R-Wert nicht angezeigt

### ISSUE THREAD

**Issue by trutzig89182** [eknoes/covidbot#176]
Bei Signal wird seit dem 9. März der r_trend (↗) nicht mehr inter dem r_value für die Bundeswerte angezeigt. Zwischen r_value und dem "." befindet sich aber ein Leerzeichen (was erkennen lässt, dass hier eigentlich etwas stehen sollte).

Im Code von https://github.com/eknoes/covidbot/blob/main/covidbot/covid_data/covid_data.py steht für den TrendValue von R:
```
if today.r_value and yesterday.r_value:
                if yesterday.r_value.r_value_7day < today.r_value.r_value_7day:
                    today.r_value.r_trend = TrendValue.UP
                elif yesterday.r_value.r_value_7day == today.r_value.r_value_7day:
                    today.r_value.r_trend = TrendValue.SAME
                if yesterday.r_value.r_value_7day > today.r_value.r_value_7day:
                    today.r_value.r_trend = TrendValue.DOWN
```

Kann es sein, dass das if nach elif Probleme bereitet. Wenn man hier die Struktur an die Festlegung von TrendValue für die anderen Werte angleicht, sollte hier stehen: 

```
if today.r_value and yesterday.r_value:
                if yesterday.r_value.r_value_7day < today.r_value.r_value_7day:
                    today.r_value.r_trend = TrendValue.UP
                elif yesterday.r_value.r_value_7day > today.r_value.r_value_7day:
                    today.r_value.r_trend = TrendValue.DOWN                
                elif yesterday.r_value.r_value_7day == today.r_value.r_value_7day:
                    today.r_value.r_trend = TrendValue.SAME
```

Das ist aber eher geraten.

Für das Leerzeichen würde ich versuchen einen Vorschlag zu submitten. Es sollte vor dem ↗ in utils.py stehen, und nicht im text in bots.py, dann wird es bei fehlendem r_trend auch nicht ausgegeben.

**Comment by eknoes** [comment]
Danke für #177 :)

**Comment by eknoes** [comment]
Ach Gott, das behebt ja nur das Leerzeichen. Sorry!

**Comment by trutzig89182** [comment]
Ja, bei der Änderung hier war ich nicht sicher genug, um einen Pull request zu machen, und ich kanns leider gerade auch nicht testen. Mein Impuls war erst mal es den funktionierenden Trendanzeigen anzupassen. Habe um den 9.3. herum  leider auch keine Änderungen gefunden, die ich dem zuordnen konnte. Davor wurde der Trend noch korrekt angezeigt.

**Comment by eknoes** [comment]
Das ist ja aber schonmal was! Mal sehen, wann ich das schaffe, danke auf jeden Fall für den Hinweis und den Leerzeichenfix, mir ist das bisher noch gar nicht aufgefallen :)

**Comment by eknoes** [comment]
Ging doch schneller als erwartet! Danke. Ist jetzt auch (gleich) deployed.

**Comment by trutzig89182** [comment]
Cool, war ja dann (nicht ganz unerwartet) doch was ganz anderes. War mir auch nicht ganz klar, warum das if hier ein Problem sein sollte. Danke für den schnellen Fix.
