### ISSUE TITLE
Bot ggf. an neues Infektionsschutzgesetz anpassen

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#178]
(Wie) können wir den Bericht abändern, sodass er gut zum neuen Infektionsschutzgesetz passt? Oder auch Befehle? 

Für das "Seit X Tagen über Y" sollten wir nun vielleicht 100, 150, 200 nehmen? Sollen wir das auch in den Bericht aufnehmen? Gibt es noch andere, sinnvolle Änderungen?

**Comment by eknoes** [comment]
> Die Notbremse tritt automatisch in Kraft, wenn die Inzidenz in einem Kreis oder einer kreisfreien Stadt drei Tage bei mehr als 100 liegt, separate Erlasse gibt es keine.
https://www.zeit.de/politik/deutschland/2021-04/infektionsschutzgesetz-coronavirus-notbremse-ausgangssperre-bundestag-faq#wie-erfahre-ich-was-gilt

**Comment by eknoes** [comment]
Außerdem sollten wir vielleicht auch ein "Seit X Tagen unter 100" aufnehmen:

> Am dritten Tag nach Unterschreiten der 100 gelten wieder die zuletzt gültigen Landesverordnungen

**Comment by errotu** [comment]
Ich würde folgende Schritte vorschlagen: (seit x Tagen unter) <25, <50, <100, (seit x Tagen über) >=100, 150, 165 (für Schulen relevant), 200

**Comment by eknoes** [comment]
Wollen wir dann diesen dritten Tag mit in den täglichen Bericht aufnehmen? Also am dritten Tag sowas zu dem Ort hinzuschreiben oder so?

**Comment by errotu** [comment]
Ja, das finde ich gut! Also einmalig als Meldung, ab dem vierten Tag dann wieder nur in dem Detailbericht.

**Comment by eknoes** [comment]
Vielleicht sollten wir aber auch das Berichtsformat anpassen - ein Großteil hat nicht so viele Orte abonniert, idR weniger als 5. Wenn wir nach BL und Städten sortieren, und das Städteformat vllt. so anpassen - ohne Gruppierung, sondern alphabetisch:

> **Städte und Landkreise**
> Darmstadt (Kreisfreie Stadt): 102,58 :arrow_lower_right:
> *(36 Neuinfektionen, 1 Todesfall, seit 2 Tagen über 100)*
>
> Göttingen (Landkreis): 73,30 :arrow_lower_right: 
> *(22 Neuinfektionen, 1 Todesfall, seit 14 Tagen unter 100)*
>
> Kassel (Kreisfreie Stadt): 204,32 :arrow_upper_right: 
> *(84 Neuinfektionen, 0 Todesfälle, seit heute über 200)*

Ich denke, dann hat man eine bessere Übersicht über die abonnierten Orte. Und das habe ich als stärkeres Feedback wahrgenommen, also dass manche lieber einen Detailbericht etc. hätten. Man könnte diese 2 Zeilen dann ja auch optional in 3 Zeilen ausbauen, wo kurz die Intensivbettenlage drin ist.

**Comment by eknoes** [comment]
Zu was zählt eine Inzidenz von exakt 100? Also ist das dann über- oder unterschritten? Irgendwie ist mir das nicht ganz klar.

**Comment by errotu** [comment]
Ich würde sagen, 100,0 ist die gleiche Kategorie wie 100,1 (also "überschritten"). Es wird ja immer von Maßnahmen "ab einer Inzidenz von 100" gesprochen, damit ist 100,0 mE bereits erfasst.

**Comment by eknoes** [comment]
Ich weiß nicht, im Gesetz steht ja:

> **Überschreitet** in einem Landkreis oder einer kreisfreien Stadt an drei aufeinander folgenden Tagen die durch das Robert Koch-Institut veröffentlichte Anzahl der Neuinfektionen mit dem Coronavirus SARS-CoV-2 je 100 000 Einwohner innerhalb von sieben Tagen (Sieben-Tage-Inzidenz) den Schwellenwert von 100, so gelten dort ab dem übernächsten Tag die folgenden Maßnahmen:

Und

> **Unterschreitet** in einem Landkreis oder einer kreisfreien Stadt ab dem Tag nach dem Eintreten der Maßnahmen des Absatzes 1 an fünf aufeinander folgenden Werktagen die Sieben-Tage-Inzidenz den Schwellenwert von 100
https://www.gesetze-im-internet.de/ifsg/__28b.html

Aber irgendwie ist es für die Inzidenz 100 einfach nicht definiert, oder?

**Comment by errotu** [comment]
Fair point. Man könnte es so interpretieren, dass 100 einfach jeweils zum status quo gehört. Wenn also die Inzidenz unter 100 war, kann sie ewig auf exakt 100 sein, die Maßnahmen werden nicht verschärft. War sie aber auf über 100, kann sie ewig auf 100 sein, die Maßnahmen werden erst gelockert, wenn mindestens 99,9 erreicht ist.

**Comment by eknoes** [comment]
Stimmt. Oh Gott, sollen wir dann einfach die 100 zu beidem nicht zählen? Was geben wir dann als Tage unter / über an?

**Comment by errotu** [comment]
Wie groß schätzt du den Aufwand ein, 100 immer dem status quo des letzten Tages über/unter 100 zuzurechnen? Wenn das programmiertechnisch komplexer wird, würde ich vorschlagen, dass wir es einfach zu den über 100 packen. Falls es doch geht, führt eine Inzidenz von exakt 100 einfach immer nur dazu, dass wir die Anzahl der Tage von gestern +1 angeben.

**Comment by eknoes** [comment]
Dann lassen wir es erstmal so, wie es ist und du es beschrieben hast. Sollte das mal öfter vorkommen, dass wir ein 100,00 haben, dann können wir es nachholen.

**Comment by errotu** [comment]
Wie besprochen sollten wir in Anlehnung an die vielen landesrechtlichen Regelungen, die auf Werktage abstellen, auch diese nennen. Vielleicht wie folgt:

> • Seit 3 Tagen (davon 1 Werktag) unter 50

**Comment by eknoes** [comment]
Es ist leider nicht so trivial zu sagen, bei welchen Werten welche der Angaben relevant ist. Habe es jetzt so gelöst:

> • Seit 211 Tagen (175 Werktagen) über 50,00, seit 7 Tagen (5 Werktagen) unter 100,00
