### ISSUE TITLE
Signal Down

### ISSUE THREAD

**Issue by JulianDerDritte** [eknoes/covidbot#184]
There was no report today and the bot isn't responding to orders. 

Steps to reproduce the bug:

1) start signal and open the chat with the corona bot
2) write "Bericht" and press the send button

Expectation: the bot sends the new report
Result: nothing happens

![Screenshot_20210503-085614_Signal](https://user-images.githubusercontent.com/83572455/116848914-f58a1c00-abed-11eb-91b9-b92b978c7f59.jpg)

Hardware: Samsung Galaxy S20+ 5G
Android:
![Screenshot_20210503-090158_Settings](https://user-images.githubusercontent.com/83572455/116849090-49950080-abee-11eb-9c6f-11b29b60faaf.jpg)

**Comment by eknoes** [comment]
Danke für dein Feedback. Wir wurden von Signal temporär gesperrt, vermutlich weil wir zu viele Nachrichten gesendet haben. Hoffentlich wird das in der nächsten Zeit aufgehoben.

**Comment by JulianDerDritte** [comment]
Gerne doch! Steht ihr im Austausch mit den Betreibern von Signal?

Bitte richte ein herzliches Dankeschön an alle DEVs und das gesamte Team aus! Ihr macht einen tollen und so wichtigen Job! ❤️

**Comment by eknoes** [comment]
Nein, soweit ich das weiß sind auch Bots eher nicht erwünscht auf Signal. @errotu

**Comment by errotu** [comment]
Habe mir gerade die [Terms of Services](https://signal.org/legal/) nochmal genauer angeschaut. Es gibt zwar die Aussage

> you must not [...] (c) _create_ accounts for our Services through unauthorized or _automated_ means

Das scheint bei uns meines Erachtens aber nicht zu passen, weil es ja nicht um die _Erstellung_ von Konten geht. Aber auch ohne Verbot unterstützt Signal Bots jedenfalls nicht ausdrücklich.

**Comment by JulianDerDritte** [comment]
Ich hatte gestern noch bei Signal den Issue gemeldet. Die Frage ist mir, wie egal das denen ist.

Habs mir nun über Telegram eingerichtet und damit nen work around.

Je nachdem wie ihr dies handhabt, würde ich verstehen, wenn ihr den issue closed.

**Comment by Leptopoda** [comment]
Also ich würde auf jeden Fall mal den Kontakt übers community forum https://community.signalusers.org aufbauen

Signal scheint sonst nicht sehr kontaktfreudig xD

**Comment by eknoes** [comment]
Bot ist jetzt wieder online, mal sehen, ob wir morgen beim Bericht wieder über ein Rate Limit kommen.

**Comment by eknoes** [comment]
Signals Rate-Limits sind hier aufgeführt: https://github.com/signalapp/Signal-Server/blob/365ad3a4f821a9e2393c5a3e1522b2c03b9dfe40/service/src/main/java/org/whispersystems/textsecuregcm/configuration/RateLimitsConfiguration.java

Wir müssen das mal richtig implementieren, leider fehlt mir aktuell die Zeit. Ich versuche mal einen schnellen Dirty-Fix.

**Comment by JulianDerDritte** [comment]
Hab den report erhalten. Bin gespannt, ob morgen auch einer kommt. 

Falls ich mich einbringen kann, lasst es mich gerne wissen.

**Comment by eknoes** [comment]
Also falls du Lust hast und Python kannst, freue ich mich über jeden PR. Muss ja nicht diesen Issue hier lösen, kann auch gerne was anderes sein :D :)

**Comment by eknoes** [comment]
Ich kann mir vorstellen, dass es hiermit zusammenhing: https://github.com/eknoes/covidbot/blob/main/resources/signal-trust-new-keys.sh

Das sollten wir lieber in semaphore implementieren, anstatt immer alle Kontakte durchzuiterieren und zu schauen, ob es einen neuen Key gibt!

**Comment by JulianDerDritte** [comment]
Kann leider nicht mit Entwicklerskills dienen. Bin PO.
- Anforderungen erfassen
- Userstories erstellen
- Priorisierung
Hier kann ich gerne helfen 😅

Ich frag mal bei meinen Entwicklern rum, ob jemand Zeit und Lust hat.
Wieviel entwickeln denn grad dran?

**Comment by eknoes** [comment]
Nur ich, @errotu macht so ein bisschen Orgasachen und kleinere Bugfixes.

Das Problem ist glaube ich die mangelnde Doku, ich würde gerne, wenn ich endlich mal wieder die Zeit habe, eine allgemeine Bot-Library rauszuziehen und den Code dann vernünftig zu dokumentieren. Leider fehlt mir dazu die Zeit, und in der wenigen Zeit baue ich dann lieber schnell neue Features ein.

**Comment by JulianDerDritte** [comment]
Ich könnte euch bei der (fachlichen) Doku unterstützen, wenn ihr möchtet?

**Comment by eknoes** [comment]
Das ist nett - ich weiß nicht so recht, ob wir fachliche Doku haben. Ich muss jetzt erstmal Zeit für die ganzen aufgestauten Issues finden :) Aber danke!

**Comment by eknoes** [comment]
Signal scheint wieder stabil zu laufen!

**Comment by JulianDerDritte** [comment]
Grad kam wieder ein Bericht 👌
Vielleicht auf eine bestimmte Anzahl an User pro push limitierten?

**Comment by eknoes** [comment]
Jetzt am Ende war es wohl auch ein RAM Problem! Wir sind jetzt mit Signal auf einen neuen Server umgezogen, das sollte hoffentlich helfen :)

**Comment by eknoes** [comment]
Hat geholfen :)
