### ISSUE TITLE
Problem mit Shell Modus

### ISSUE THREAD

**Issue by trutzig89182** [eknoes/covidbot#186]
Hi, 
ich habe versuch Lokal eine Version des Bots zu installieren. Leider hat bei mir das Starten des Programms im Shell Modus nicht funktioniert. Das Aufrufen von --help hat noch geklappt. 
Ist das ein allgemeineres Problem oder war ich einfach nur zu doof, bei der Installation und der Konfigurierung alles richtig zu machen? Bin nur etwas irrtiert, weil ich in __main__.py auch shell nicht als argument gefunden habe.
LG

**Comment by eknoes** [comment]
Sorry, das README ist nicht aktuell und Docs sind quasi nicht vorhanden. Ich bin leider gerade zeitlich hart limitiert. Du solltest es mit `python -m covidbot --platform interactive` starten können. Dafür muss allerdings eine MySQL DB laufen und ein `config.ini` file existieren mit der Datenbank - dann sollte es gehen:

```
[DATABASE]
HOST = localhost
PORT = 3307
USER = root
PASSWORD = covid_bot
DATABASE = covid_test_db
```
