### ISSUE TITLE
Intensivbetten auf Threema und FB Messenger

### ISSUE THREAD

**Issue by errotu** [eknoes/covidbot#187]
Auf Threema und Facebook Messenger zeigt der tägliche Bericht derzeit keine Intensivbetten an (anders als bei Telegram).

**Comment by eknoes** [comment]
Da gibt es eigentlich nichts plattformabhängiges, es kann nur sein, dass du es über die Einstellungen ausgeschaltet hast. Die gelten auch für den nicht-Beta Bericht, das ist ein bisschen suboptimal.

**Comment by eknoes** [comment]
Ja das stimmt, im Default ist es raus, weil wir in dem neuen Bericht die Intensivbetten draußen haben. Wollen wir das noch ein paar Tage so lassen und dann migrieren wir eh bald auf den neuen Bericht?

**Comment by errotu** [comment]
Ich bin gerade auch nochmal das interne Feedback durchgegangen. Tatsächlich werden die fehlenden Intensivbetten immer wieder bemängelt. Ich wäre deshalb eher dafür, sie kurzfristig wieder im Default einzustellen und vielleicht auch beim neuen Bericht nicht rauszunehmen, sondern nur explizit darauf hinzuweisen, wie man sie rausnehmen kann.
