### ISSUE TITLE
Impfdaten

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#190]
Wir sollten auf die Excel Tabelle des RKI umstellen (https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html), die impfdashboard.de Seite liefert die Daten für die Bundesländer nicht an bspw. Werktagen und hat auch nicht alle Informationen.

**Comment by errotu** [comment]
[Hier](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland) gibt es auch eine csv-Datei, vielleicht ginge das noch einfacher?

**Comment by eknoes** [comment]
Wir müssen uns Gedanken machen, wie wir mögliche Drittimpfungen einbeziehen / Wie die Daten verfügbar sind

**Comment by errotu** [comment]
Finde den letzten Punkt inzwischen immer wichtiger. Wenn wir die Daten von Github aus der Landkreisdatei ziehen, hätten wir dort auch die Drittimpfungen (Spalte "Impfschutz").

Als allgemeine Terminologie schlage ich folgendes vor:

> Auffrischungsimpfungen
> Erstimpfungen
> Vollständige Erstimmunisierung

In der Textform wäre das dann:

> So haben 58.507.255 (70,32%) Personen in Deutschland mindestens eine Impfdosis erhalten, 56.427.564 (67,82%) Menschen sind bereits vollständig durch Impfungen erstimmunisiert. Bei xxx (xx,xx%) Menschen haben eine Auffrischungsimpfung erhalten. 

In der Grafik sollte ein dritter Schatten (vielleicht in einem helleren Blauton) zu den bestehenden beiden hinzukommen (ganz unten). Also Auffrischungsimpfungen als Teilmenge der vollständig Geimpften als Teilmenge der Erstgeimpften.

**Comment by errotu** [comment]
Den Infotext zu den Impfungen passe ich mal, damit wir die Einfachimpfung durch Johnson und Johnson berücksichtigen.

**Comment by errotu** [comment]
Habe die Terminologie jetzt mal angepasst. Nur bei der Grafik wurde es noch nicht übernommen. Die sind gecached, oder? Dürfte sich dann ja mit den nächsten neuen Zahlen aktualisieren.

**Comment by eknoes** [comment]
Genau, die sind gecached. Danke! Mal sehen, ich peile an das spätestens bis zum nächsten Wochenende endlich zu erledigen. Es ist viel zu relevant, dafür, dass es nicht Teil des Bots ist.
