### ISSUE TITLE
Bot spamt

### ISSUE THREAD

**Issue by yorickreum** [eknoes/covidbot#191]
Habe den Bericht für gestern (19.05.) nun fünfmal bekommen innerhalb der letzten Stunde.

**Comment by dominiks** [comment]
Schickt mir den Tagesbericht ca alle 15 Minuten. Habe den Bot nun erstmal geblockt.

**Comment by eknoes** [comment]
Das tut uns sehr leid, das sollte nicht passieren. Ich gehe auf Fehlersuche, offenbar betrifft es den Zeitraum von 0 Uhr bis die nächsten Daten kommen - jetzt ist alles wieder "normal".

**Comment by eknoes** [comment]
Der Bug ist aufgetreten zwischen 0 Uhr und den neuen RKI Daten. Das lag daran, dass der Updater erst in diesem Zeitraum läuft, also wenn die aktuellsten Daten < Heute sind. Deshalb hat es um 0 Uhr angefangen, und gegen 5 Uhr aufgehört. Danach ging noch einmal der "korrekte" Bericht raus.

Der Updater hat bisher, auch wenn es keine neuen Daten gab, alle aggregierten Daten neu berechnet. Da wir die Zahlen nur auf Landkreisebene bekommen, rechnen wir uns die Bundesländer / bundesweiten Zahlen selbst aus. Dabei wurde das Datum der aggregierten Zahlen nicht verändert, allerdings speichern wir auch in einer Spalte, wann wir die Zahlen geupdated haben. Diese wurde immer auf "Jetzt" gesetzt, auch wenn sich diese aggregierten Daten nicht verändert haben. Das war bisher nie ein Problem (außer unnötigem Rechenaufwand) und ist deshalb nicht aufgefallen - auch, weil es ja nur zwischen 0 Uhr und den neuesten Daten passiert, danach startet der Updater ja nicht mehr.

Gestern (8ed65da2226ed2d4df95801c29053c08763a567f) haben wir jedoch den Vergleich geändert, wie wir checken, ob neue Berichte versendet werden. Das lief vorher ab wie folgt (Hier: https://github.com/eknoes/covidbot/blob/main/covidbot/report_generator.py#L35):
1. Wir checken, wann wir dem Nutzer das letzte Mal einen Bericht gesendet haben (meist MessageType = "cases-germany)
1. Wir checken, von wann die letzten zugehörigen Daten sind (Hier von welchem Tag die zugehörigen Daten sind)
1. Wenn die Daten neuer sind versenden wir einen Bericht 

Das habe ich gestern verbessert:
Da wir mit #189 u.A. auch Impfdaten versendet haben, hat das nicht mehr geklappt: Hier liegt bei den neuesten Daten das Datum einen Tag zurück (heute werden bspw. Impfdaten für den 19.5. veröffentlicht), der Check würde nur jeden zweiten Tag erkennen, dass ein Bericht versendet werden muss. Also habe ich Schritt 2 geändert zu:
2. Wir checken, wann genau die neuesten Daten in die Datenbank geschrieben wurden

Durch den am Anfang beschriebenen Fehler, dass der Updater zwischen 0 Uhr und den neuesten Daten (heute 5 Uhr) jedoch genau diesen Timestamp alle 15 Minuten bei den aggregierten Daten auf das aktuelle Datum gesetzt hat, haben wir alle 15 Minuten neue Berichte versendet.
