### ISSUE TITLE
"Sleep-Modus" für Bot einführen

### ISSUE THREAD

**Issue by errotu** [eknoes/covidbot#194]
Ich habe das Feedback bekommen, dass manche Leute den Bot nun abbestellen, weil sie tägliche Updates für nicht mehr notwendig halten. Kann ich durchaus nachvollziehen. Dabei kam die Idee auf, dass man einen "Sleep-Modus" mit einem bestimmten Infektionswert definieren kann. Erst wenn einer der abonnierten Orte den Infektionswert übersteigt, erhält man den Bericht wieder.
Was hältst du davon, @eknoes?

**Comment by eknoes** [comment]
Finde ich eine nette Idee, denke aber nicht, dass ich das so schnell umsetzen kann. Man kann auch den Infektionsbericht abbestellen, und bekommt ihn dann nur noch auf Anfrage mit "Bericht" - sollten wir das vielleicht mal promoten?

**Comment by errotu** [comment]
Ja, das wäre auf jeden Fall eine gute Alternative. Der Vorteil des Sleep-Modus wäre, dass wir zwar in Vergessenheit geraten können, aber bei steigenden Zahlen auch unmittelbar wieder aktiv wären. Wenn das aber im Moment eher zu viel Aufwand ist, ist ein Newsletter, der auf das Abbestellen aufmerksam macht, mit Sicherheit eine gute Alternative!

**Comment by eknoes** [comment]
Ok. Vielleicht baue ich das einfach ein, ich fände es auch praktisch. Ich würde es ab einer fixen Inzidenz machen, 10 vielleicht?

**Comment by errotu** [comment]
Finde 10 gut (wäre jedenfalls die Inzidenz, die ich mir auch eingestellt hätte). Meinst du, es ist deutlich aufwändiger, die Möglichkeit individueller Werte einzubauen? Könnte mir schon vorstellen, dass einige es erst bei höheren (bspw. 25/35) Werten interessant finden.

**Comment by eknoes** [comment]
Ja, aktuell sind alle unsere Einstellungen so, dass man nur boolean-Werte speichern kann, deshalb wäre es am einfachsten eine Einstellung dafür zu basteln die auch nur Ja oder Nein kennt!
