### ISSUE TITLE
Hospitalisierungsrate einpflegen

### ISSUE THREAD

**Issue by errotu** [eknoes/covidbot#195]
So wie ich die aktuelle Diskussion mitbekomme, soll demnächst [stärker auf die Hospitalisierungsrate als auf die Inzidenzzahlen geachtet werden](https://www.mdr.de/nachrichten/deutschland/panorama/corona-inzidenz-hospitalisierung-100.html). Derzeit veröffentlicht das RKI dazu noch nichts über die Schnittstellen (wenn ich mich nicht täusche). Sobald das aber der Fall ist (und in der öffentlichen Diskussion im Allgemeinen darauf zurückgegriffen wird, insbesondere rechtliche Maßnahmen daran ausgerichtet werden), sollten wir sie wohl auch in den Bot aufnehmen.

**Comment by errotu** [comment]
Die einzige Datenquelle, die ich im Moment für die Hospitalisierungsrate finde, [ist diese](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Klinische_Aspekte.html) (leider im xlsx-Format). Leider ist die deutschlandweit und nicht regionenspezifisch. Außerdem finde ich nur altersbezogene Hospitalisierungsraten, wie man den bundesweiten Schnitt daraus errechnen kann (können soll), ist mir nicht klar.

**Comment by eknoes** [comment]
Hier scheint es seit heute auch die Hospitalisierungsinzidenz für alle Bundesländer in maschinenlesbar zu geben: https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland

**Comment by errotu** [comment]
Ich lege hier mal die möglichen ToDos ab, die ich noch im Kontext der Hospitalisierung sehen würde:

- [ ] Trends anzeigen
- [ ] Hospitalisierung unter "Daten [ORT]" einfügen
- [ ] Graphen für Hospitalisierungsinzidenz anbieten (analog zur 7-Tage-Inzidenz)
- [ ] Säulendiagramm für Krankenhauseinweisungen anbieten (analog zu Infektionen)
- [ ] Überprüfen, inwieweit Grenzwerte für bestimmte Schwellen in der Grafik Sinn machen (vgl. hierzu bspw. [Niedersachsens Warnstufen](https://www.niedersachsen.de/Coronavirus/aktuelle_lage_in_niedersachsen/niedersachsen-und-corona-aktuelle-leitindikatoren-203487.html))

**Comment by eknoes** [comment]
Das mit dem Säulendiagram passt imho nicht. Das ist ja die Summe der hospitalisierten COVID-19-Fälle mit Meldedatum innerhalb der letzten 7 Tage, durch die Säulen wirkt es so als ob die an diesem Tag eingeliefert wurden. Würde dann auch eher das so Inzidenzmäßig gestalten?

**Comment by eknoes** [comment]
Kannst du mal wegen der Schwellwerte schauen, ob es da was einheitliches gibt? Andererseits ist diese Inzidenz eh ein Wert zwischen 0 und glaube in Hochzeiten mal 6, von daher sind da mögliche Schwellwerte glaube ich standardmäßig schon ganz gut eingezeichnet.

**Comment by eknoes** [comment]
Zu Trends: Würde ich hier gerne weglassen, weil wir jedes mal die komplett neuen Daten ziehen, da die auch im Nachhinein aktualisiert werden. Der Tagesaktuelle Wert ist dadurch immer etwas niedriger, wird am Folgetag (nach oben) korrigiert und denke da durch machen die Trends keinen Sinn.

**Comment by eknoes** [comment]
Tweet sieht so aus: https://twitter.com/D64_Covidbot/status/1443252643963539463

**Comment by eknoes** [comment]
@errotu Hast du Lust auch einen Newsletter zu entwerfen?

**Comment by errotu** [comment]
Bei den Schwellwerten scheint es nichts einheitliches zu geben, habe mir gerade nochmal testweise ein paar angeschaut ([Thüringen, Sachsen, Sachsen-Anhalt](https://www.mdr.de/nachrichten/deutschland/panorama/corona-bundeslaender-hospitalisierungsrate-100.html)).

Könnte man den Trend nicht über einen Blick [ins Archiv](https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/tree/master/Archiv) einfügen, so dass man gar nicht auf korrigierten Zahlungen zurückgreift? Mir fällt es jetzt gerade nur optisch auf, weil es der einzige Satz ohne bunte Pfeile ist.

Newsletter entwerfe ich heute oder morgen. Danke dir für die ganze Arbeit!

**Comment by errotu** [comment]
Die Grafik scheint derzeit aber nicht korrekt generiert zu werden. Die Inzidenz liegt laut Text bei 1,6, wird in der Grafik aber als relativ genau 1,0 angezeigt.

**Comment by eknoes** [comment]
Das war ein Fehler in der Achsenbeschriftung, wir haben den Nachkommapart weggeschnitten. Jetzt passt es.

**Comment by eknoes** [comment]
Zu den Trends: Dann müssten wir die Daten doppelt sammeln, das finde ich ein bisschen zu aufwendig.
