### ISSUE TITLE
SignalBot schickt seit gestern keine Nachrichten mehr und reagiert nicht 

### ISSUE THREAD

**Issue by markum** [eknoes/covidbot#196]
SignalBot schickt seit gestern keine Nachrichten mehr und reagiert nicht auf Befehle wie Abo oder Info.

**Comment by errotu** [comment]
Leider gab es in den vergangenen Tagen Probleme beim Abruf der Daten vom RKI, die zu fehlerhaften Zahlen geführt haben. Wir haben den Bot - weil die Fehler leider mitten in unsere Urlaubszeit fallen - deshalb in die Sommerpause schicken müssen. Ab dem 22. August werden aller Voraussicht nach wieder tägliche Updates verschickt.

Eine entsprechende Info-Nachricht sollte auch eigentlich an alle Nutzer:innen verschickt worden sein ([hier der entsprechende Twitter-Thread](https://twitter.com/D64_Covidbot/status/1421142468490313731)), leider gab es aber Probleme beim Versand an die Signal-Nutzer:innen. Wir werden [die Webseite](https://covidbot.d-64.org/) kurzfristig updaten, damit die Info auch dort enthalten ist.

**Comment by markum** [comment]
@errotu : Ich habe nur folgende Nachricht erhalten: "Heute Morgen hat sich leider der Fehlerteufel bei uns eingeschlichen. Wir suchen derzeit nach der Ursache, die von uns veröffentlichten Zahlen sind (glücklicherweise) deutlich zu hoch: Die bundesweiten Neuinfektionen für heute liegen bei 3520. Alle korrekten Zahlen gibt es bis dahin unter https://corona.rki.de" Dem war nicht zu entnehmen, dass das Bot so lange pausieren wird. Aber jetzt wo ich es weiß, alles klar.

**Comment by errotu** [comment]
Es gab danach noch eine weitere ausführliche Nachricht, die leider auf Signal bei einigen nicht zugestellt wurde. Entschuldige!
