### ISSUE TITLE
X-Achse der Statistik-Grafik anpassen

### ISSUE THREAD

**Issue by errotu** [eknoes/covidbot#197]
Inzwischen gibt es den Bot so lange, dass die X-Achse der Statistik-Grafik etwas unübersichtlich geworden ist. Ich würde vorschlagen, dass wir dort nur noch die Monate, nicht mehr jede Woche beschriften.

**Comment by eknoes** [comment]
Welche Statistik Grafik meinst du?

**Comment by errotu** [comment]
Die Nutzer:innenübersicht über /Statistik

**Comment by eknoes** [comment]
Ist deployed
