### ISSUE TITLE
Formulierung in Bezug auf Hospitalisierung korrekt?

### ISSUE THREAD

**Issue by trutzig89182** [eknoes/covidbot#202]
Unter der Rubrik Infektionszahlen in Deutschland heißt es im letzten Satz:

> „In den letzten 7 Tagen wurden X Personen wegen Covid19 ins Krankenhaus eingewiesen.“

Soweit ich weiß, sind in den Hospitalisierungszahlen auh Menschen erfasst, die aus anderen Gründen ins Krankenhaus eingewiesen werden, bei denen dann aber eine unbemerkte Corona-Infektion entdeckt wird. Dann wäre „wegen Covid19 ins Krankenhaus eingewiesen“ nicht ganz korrekt.

Wenn man die Formulierung nicht unnötig kompliziert machen will, könnte man einfach das „wegen“ durch ein „mit“ austauschen.

Gerne sagen, wenn ich da was falsch verstehe. Ansonsten würde ich einen pull request vorbereiten.

**Comment by eknoes** [comment]
Ich denke du liegst da richtig. Kannst du gerne ändern! :) Danke!

**Comment by errotu** [comment]
Nur noch eine Ergänzung von der [Webseite des RKI](https://www.rki.de/SharedDocs/FAQ/NCOV2019/FAQ_Liste_Epidemiologie.html#FAQId16715632):

> **Bei der Berechnung der 7-Tage-Hospitalisierungsinzidenz wird der Grund für die Hospitalisierung nicht berücksichtigt, da diese Informationen nicht immer vollständig und valide vorliegen.** Bei der Gruppe der hospitalisierten Personen handelt es sich bzgl. Aufnahmegründen und Verläufen um eine sehr heterogene Gruppe. Entscheidungen über die Aufnahme sind nicht immer an die Schwere der Erkrankung geknüpft (z. B. junge Kinder, ältere Erwachsene zur Beobachtung). Meldepflichtig gemäß Infektionsschutzgesetz ist jede Hospitalisierung in Bezug auf COVID-19. **Das bedeutet, dass der Grund der Aufnahme in Zusammenhang mit der COVID-19-Erkrankung steht, aber ein direkter kausaler Zusammenhang zum Zeitpunkt der Meldung noch nicht hergestellt werden muss.** Dies soll eine niedrigschwellige, zügige und aufwandsarme Meldung gewährleisten. **Wird bei Aufnahme der betroffenen Person jedoch deutlich, dass die Krankenhausaufnahme in keinem Zusammenhang mit der COVID-19-Diagnose steht, z.B. bei einem Verkehrsunfall, dann besteht keine Meldepflicht.**

Es ist also kompliziert. Ich finde deinen Vorschlag von "mit" aber auch gut, weil er mir diesen Zwischenbereich zwischen Kausalität und Korrelation ganz passabel abzudecken scheint.

**Comment by trutzig89182** [comment]
Habe einen entsprechenden Pull request gemacht (auch wenn ich anscheinend zu deppert bin, um ihn direkt mit dem Issue zu verlinken).

"Mit" ist nicht besonders präzise, aber alternativ würden mir nur sehr komplizierte Formulierungen einfallen, die für den den Zweck des Bots nicht geeignet wären.

**Comment by eknoes** [comment]
Top, ist drin. Danke!
