### ISSUE TITLE
Zeitabschnitte mit vielen Nachmeldungen kennzeichnen

### ISSUE THREAD

**Issue by psirotkin** [eknoes/covidbot#205]
Ich glaube, es ist inzwischen Konsens, dass die RKI-Daten zur Hospitalisierung wegen der vielen Nachmeldungen für die jeweils letzten Wochen nicht aussagekräftig sind (siehe z.B. https://www.ndr.de/nachrichten/info/Hospitalisierungsrate-zeigt-nur-noch-die-Haelfte-der-Corona-Patienten,hospitalisierungsrate102.html). Um die Unsicherheit zu zeigen, könnte man z. B. die letzten 21 Tage straffieren und einen entsprechenden Hinweis einfügen. Das gleiche wäre auch für die letzten 1-2 Tage der Neuinfektionen möglich.

**Comment by eknoes** [comment]
Ich habe die Grafik jetzt erstmal komplett entfernt, leider schaffe ich es aktuell zeitlich nicht das besser darzustellen.
