### ISSUE TITLE
Signal: Bot empfängt keine Steuerungsbefehle

### ISSUE THREAD

**Issue by rickcrash** [eknoes/covidbot#206]
Am 18.11.2021 um 13:54 Uhr habe ich in den Chat mit dem Bot "Hilfe" geschrieben. Die Nachricht hat mein Gerät verlassen (1 Haken), wurde jedoch nicht zugestellt (kein 2. Haken).

Bei weiteren Nachrichten um 17:30 und am 19.11.2021 um 8:08 und 9:30 Uhr das gleiche.

Vielen Dank 
Rick

**Comment by errotu** [comment]
Danke für die Meldung. Ich konnte den Fehler bei mir reproduzieren. Nach einem Neustart des Bots geht es nun wieder. Wird dir auch wieder geantwortet?

**Comment by rickcrash** [comment]
Ja, läuft wieder. Perfekt!
