### ISSUE TITLE
Mastodon - Tägliche Berichte werden nicht mehr versendet

### ISSUE THREAD

**Issue by errotu** [eknoes/covidbot#207]
Seit dem 01. November werden auf Mastodon keine täglichen Berichte mehr versendet, es wird nur auf individuelle Anfragen beantwortet.

**Comment by eknoes** [comment]
Da mittlerweile so viele Intensivbetten belegt sind, wurde unser Tweet zu lang, der Bot ist gecrashed und hat dann auch den Mastodon Part nicht mehr erledigt. mit 4da3136 catchen wir jetzt die Fehler und senden sie an uns, dann bekommen wir sowas mit!
