### ISSUE TITLE
Grafik - Skala nach 500 erweitern

### ISSUE THREAD

**Issue by errotu** [eknoes/covidbot#208]
Aktuell geht die Skala unserer Inzidenzgrafiken nur bis 500. Das sollten wir dringend erweitern, bei den regionalen Berichten reicht es schon länger nicht aus.

**Comment by trutzig89182** [comment]
Wenn ichs richtig sehe, müsste das nur eine Anpassung in zwei Zeilen von visualizations.py sein, oder?

https://github.com/eknoes/covidbot/blob/b4133989ddf171a1cc0f6462d8f3cddbb53b5310/covidbot/covid_data/visualization.py#L390

https://github.com/eknoes/covidbot/blob/b4133989ddf171a1cc0f6462d8f3cddbb53b5310/covidbot/covid_data/visualization.py#L429

Ich mach gelich mal einen pull request. Allerdings komme ich mit den Anweisung im Readme um Covidbot in der Shell laufen zu lassen nicht zurecht und kanns darum selbst nicht testen.

Ergänzend könnte man überlegen, ob man die Skala dynamischer gestalten kann. Die 35 und 165 sehen bei mir sehr reingeknubbelt aus. M. E. wäre es da sinnvoll, diese Schwellen ab einer gewissen höhe nicht mehr anzuzeigen.

![image](https://user-images.githubusercontent.com/63927781/143439289-1816ae86-f8ac-442f-9c1a-58c31ec79696.png)

**Comment by trutzig89182** [comment]
Kleine Ergänzung: Höchstwert für 7-Tage-Inzidenz liegt aktuell bei 1688, niedrigster Wert bei 85. Ob sich das für eine fest definzierte Sakala beides gut darstellen lässt, ist glaube ich auch ohne die 35-, 50- und 165-Werte fragwürdig.

**Comment by eknoes** [comment]
Danke für deinen PR! Eigentlich können wir doch, dadurch dass es die Bundesnotbremse sowieso nicht mehr geben wird (?, @errotu), diese ganzen von uns gegebenen Stufen streichen und wieder auf die Autoskala setzen, oder? Wir haben diese Werte ja nur eingebaut, um die für die Notbremse wichtigen Werte hervorzuheben.

**Comment by errotu** [comment]
Ja, hast völlig recht. Auf absehbare Zeit spielen die Zwischenwerte keine Rolle.

**Comment by trutzig89182** [comment]
> Eigentlich können wir doch, dadurch dass es die Bundesnotbremse sowieso nicht mehr geben wird (?, @errotu), diese ganzen von uns gegebenen Stufen streichen und wieder auf die Autoskala setzen, oder? Wir haben diese Werte ja nur eingebaut, um die für die Notbremse wichtigen Werte hervorzuheben.

Denke auch, dass das die eleganteste Lösung ist, da ja selbst wenn es wieder entsprechende Werte geben wird, sie ganz sicher nicht genau die bisher ausgewiesenen sein werden und man in diesem Fall also ohnehin noch mal dran müsste.
