### ISSUE TITLE
Prozent des Textes 'Auffrischungsimpfung erhalten' im Bundesland falsch

### ISSUE THREAD

**Issue by MAGICCC** [eknoes/covidbot#212]
Hallo,

Mir ist aufgefallen, dass mit https://github.com/eknoes/covidbot/commit/15677ca22ff027b090a19f1f722856cb8c5bc0e4 etwas falsch ist 

```
Hessen: 70,96% min. Erstimpfung
• 67,48% vollständig erstimmunisiert
• 67,48% Auffrischungsimpfung erhalten
• Ø 35.640 Impfungen am Tag
```

https://github.com/eknoes/covidbot/blob/main/covidbot/report_generator.py#L360
Müsste da nicht `vacc_booster` hin?

**Comment by eknoes** [comment]
Oh Gott, klar. Danke, dass dir das aufgefallen ist :) Fixe ich sofort!
