### ISSUE TITLE
Bericht aufteilen

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#218]
Der Bericht hat ja mehrere Abschnitte. Ich frage mich, ob es die Lesbarkeit verbessert, diese in Nachrichten mit Grafiken aufzuteilen.

**Comment by errotu** [comment]
Fände ich nicht so gut, glaube ich. Habe jetzt schon einen Bericht, der so groß ist, dass er sich aufteilt, und finde es direkt unübersichtlicher. Gerade wenn Grafiken dazwischen sind, könnten die ersten Nachrichten untergehen.
