### ISSUE TITLE
Facebook Messenger und Threema down

### ISSUE THREAD

**Issue by errotu** [eknoes/covidbot#222]
Aktuell antwortet der Bot weder auf Facebook Messenger noch auf Threema. Tägliche Updates werden aber verschickt. Auf anderen Messengern reagiert er.

**Comment by eknoes** [comment]
Geht wieder. Bei den beiden werden dem Bot Nachrichten per HTTP zugestellt, und die beiden Dienste hatten dafür noch covidbot.eknoes.de statt covidbot.d-64.org genutzt - ich habe meine Domain aber umgezogen, und bin irrtümlich davon ausgegangen, dass diese nicht mehr genutzt wird und hab den Eintrag gelöscht. Sorry!
