### ISSUE TITLE
Dopplung bei Wiedergabe von Impfdaten

### ISSUE THREAD

**Issue by trutzig89182** [eknoes/covidbot#226]
Auf den Text mit den aktuellen Impfdaten folgt noch einmal eine Auflistung mit den absoluten Zahlen der Erst-, Zweit- und Booster-Impfungen. Die Zahlen sind aber schon im Text enthalten und machen es daher nur unnötig kompliziert. 

 <img src="https://user-images.githubusercontent.com/63927781/148699611-f041997d-b036-4ba1-9292-006b4581230c.png" alt="Text in Messanger: 
💉 Impfdaten (Deutschland) / Am 07.01.2022 wurden 648.129 Dosen verimpft. So haben 61.987.433 (74,51%) Personen in Deutschland mindestens eine Impfdosis erhalten, 59.683.677 (71,74%) Menschen sind bereits vollständig geimpft, 35.144.664 (42,24%) Menschen haben eine Auffrischungsimpfung erhalten. Bei dem Impftempo der letzten 7 Tage werden 423.300 Dosen pro Tag verabreicht. / Verabreichte Erstimpfdosen: 61.987.433 / Verabreichte Zweitimpfdosen: 59.683.677 / Verabreichte Auffrischungsimpfungen: 35.144.664" width="50%"> 

Reproduzieren: "Impfung" in Chatdialog eingeben.

Ich schlage vor, die Dopplung zu löschen, da sie bei den ohnehin sehr vielen Informationen (tägliche Neuimpfunge, Absolute Impfunge, Prozentuale Imfpungen …) es unnötig noch komplizierter machen. Ich habe jedenfalls ernstmal gedacht, dass seien noch mal neue Zahlen, bevor ich verstanden habe, dass es nur eine Widerholung ist.

 Vorschlag: 2b5bbb0005354c65e5a370ea6cd2ae98827ca1af

**Comment by eknoes** [comment]
Ja stimmt, finde ich gut, mach gerne einen PR auf. Ich bin mir aber noch nicht so sicher, ob es nicht auch gut ist die Zahlen so gut sichtbar zu haben, sodass man den Text eben nicht lesen muss.

**Comment by trutzig89182** [comment]
@eknoes Ja, verstehe den Überblick auch. Aber So ist es eher irritierend. Man könnte natülrlich die Info auch oben aus dem Text rausnehmen Und beim Überblick dann noch die Prozente Ergänzen. 

Also Quasi: 

> Am 07.01.2022 wurden 648.129 Dosen verimpft. Bei dem Impftempo der letzten 7 Tage werden 423.300 Dosen pro Tag verbreicht. 
Verabreichte Erstimpfdosen: 61.987.433 (74.,51 %)
Verabreichte Zweitimpfdosen …

BTW, typographisch wäre ein geschütztes Leerzeichen zwischen Zahl und % korrekt. Aber das sollte wenn mal konzertiert für die verschiedenen Dialoge angepasst werden.

**Comment by trutzig89182** [comment]
Vielleicht einfach sagen, was präferiert wird, dann bereite ich einen PR für die enstprechende Lösung vor.

**Comment by eknoes** [comment]
Was sagt @errotu dazu?

**Comment by errotu** [comment]
Ich finde #2b5bbb0 gut, die Dopplung ist tatsächlich nicht optimal und wenn wir es anders auftrennen wird wahrscheinlich nicht sicher deutlich, dass es sich um die gleichen Werte, nur eine unterschiedliche Darstellung handelt.

**Comment by trutzig89182** [comment]
PR ist raus. Falls ihr Feeback dazu habt, dass in einen PR noch andere Infos rein sollten oder irgendwas beim PR anders/besser gemacht werden kann, bitte her damit. Bin da sehr unerfahren und versuche dazu zu lernen. :)

**Comment by eknoes** [comment]
Top, danke für den PR. Alles super, ein Glück hab ich gestern noch unsere Tests repariert :D Ist auch deployed :)
