### ISSUE TITLE
Thank you for your project

### ISSUE THREAD

**Issue by Lukas2112** [eknoes/covidbot#238]
I just wanted to thank all the people involved in this project for initiating, developing and running the "Covidbot" project - THANK YOU for your so enormously important work,  @eknoes , @errotu , @HannesHil , @trutzig89182 , @MAGICCC and @haupas  and all those with reporting bugs and suggesting new features!

**Comment by errotu** [comment]
Thank you very much for the compliments! We appreciate it a lot!
