### ISSUE TITLE
Add Divi Intensivbettenregister

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#3]

**Comment by errotu** [comment]
Aktuelle Problembeschreibung: Die Divi-Intensivbettenregister sind zwar [öffentlich abrufbar](https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/cf7a8cb4b68048c28a78833eeb770839), aber nicht frei lizenziert:

> Bitte kontaktieren Sie DIVI, sollten Sie die Daten weiterverwenden wollen.Datenquelle: DIVITerms of Use: DIVICredits (Attribution): DIVI

Eine Anfrage zur Nutzung läuft derzeit.

**Comment by errotu** [comment]
Gegenüber der Divi besteht wohl kein Anspruch aus IFG oder IWG, weil es sich nicht um eine öffentliche Institution handelt, siehe #50 (Hervorhebungen von mir). Die einzelnen Krankenhäuser anzufragen, wäre für uns mit Sicherheit zu aufwendig.

> Die DIVI stellt ihre Zahlen für die Intensivbettenbelegung nicht allgemein frei lizenziert bereit, sondern man immer explizit anfragen muss (und wir darauf seit drei Wochen keine Antwort erhalten).
> Die DIVI ist ein e.V. Die Mitglieder bestehen aus Ärzten, also Privatleuten. Einige dieser Ärzte arbeiten bei Krankenhäusern in öffentlich-rechtlicher Trägerschaft. Das trifft aber sicher nicht auf alle Mitglieder zu. **Eine Konstruktion eines Anspruchs aus einem IFG oder dem IWG gegenüber DIVI ist dann wohl nicht möglich.**
> Gegenüber den öffentlich-rechtlichen Trägern könnte man Informationszugangsansprüche nach dem jeweiligen Landes-IFG gelten machen. Ein Anspruch auf Weiterverwendung der Daten ergibt sich dann aus § 2a IWG. Gegenüber Krankenhäusern in privater Trägerschaft könnten auch Ansprüche aus dem jeweils geltenden Landes-IFG bestehen. Private Einrichtungen unterfallen dem IFG regelmäßig aber nur soweit eine Behörde sich dieser Person zur Erfüllung ihrer öffentlich-rechtlichen Aufgaben bedient (Vgl. § 1 Abs. 1 S. 3 IFG Bund; viele Landes-IFG sind an diese Regelung zumindest angelehnt). Ob dies der Fall ist, kann ich mangels Kenntnis des „Krankenhausrechts“ aber nicht beurteilen.
> Sofern ein Krankenhaus dem Anwendungsbereich eines Landes-IFG unterfällt, besteht grds. ein Anspruch auf Zugang zu der Information. Dieser darf nur gestützt auf einen Ausnahmegrund verweigert werden. Ohne nähere Prüfung gehe ich aber nicht davon aus, dass es sich bei den Informationen um besonders schutzwürdige Informationen handelt, die etwaigen Ausnahmegründen nach den Landes-IFG unterfallen. Ich gebe aber zu bedenken, dass ein solcher Anspruch notfalls eingeklagt werden müsste.
> Informationen müssen grds. in dem angefragten Format bereitgestellt werden, es sei denn, für die Behörde ist damit ein „unverhältnismäßiger Aufwand“ verbunden. Hier würde ich davon ausgehen, dass ein Gericht sich schwer damit tuen sollte, einen solchen Aufwand zu erkennen. Schließlich ist davon auszugehen, dass die Informationen von DIVI gleichsam nicht händisch zusammengetragen werden, sondern in entsprechenden Formaten bereitgestellt werden. Das ist natürlich aber nur eine Annahme.

**Comment by eknoes** [comment]
Wir haben ja noch keine Antwort, aber auf mich wirkt es als dass wir die Divi Daten von hier nutzen könnten: https://www.intensivregister.de/#/aktuelle-lage/reports

**Comment by errotu** [comment]
Stimmt, das sieht gut aus. Würde ich auch so sehen!

**Comment by errotu** [comment]
Offizielle Freigabe liegt nun auch vor!

**Comment by eknoes** [comment]
Wie wollen wir die aufbereiten? Die Daten liegen auf Landkreis Ebene vor, wir könnten einen Extra-Befehl einführen. Oder vielleicht in den Detailbericht eines Ortes die aktuelle Krankenhausauslastung packen? https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/8fc79b6cf7054b1b80385bda619f39b8_0/data

**Comment by errotu** [comment]
Detailbericht des Ortes fände ich gut! Mit extra Befehlen sollten wir 
meiner Meinung nach eher sparsam sein. Ich glaube, die werden wirklich 
nur von Power-Usern verwendet.
