### ISSUE TITLE
"Wusstest du schon" - am Ende des Berichts

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#64]
Ab und zu gibts neue Features, allerdings wollen wir nicht jedes Mal einen Newsletter schreiben. @errotu, dein Vorschlag war am Ende eines Tagesberichts einen Satz á la "P.S.: Wusstest du schon, dass du uns einfach direkt eine Feedbacknachricht senden kannst?", oder?

**Comment by errotu** [comment]
Genau so habe ich es mir vorgestellt. Vielleicht könnten wir es so bauen, dass wir fünf bis zehn Tipps erstellen und die zufällig bei jedem zweiten oder dritten Bericht angezeigt werden.

**Comment by Lukas2112** [comment]
That sounds great! Perhaps the meanwhile frequently spread fake news via Telegram in connection with the coronavirus SARS-CoV-2 and the resulting disease COVID-19 could be taken as an opportunity to refute exactly this information with reliable scientific data?

**Comment by eknoes** [comment]
Ich denke wir sollten nur Botbezogene Tipps verbreiten und auch nicht zu häufig, sonst werden die zu repetitiv. Außerdem denke ich sollten wir es bei nicht-redaktionellen Inhalten belassen, so haben wir klare Quellen und bringen einfach nur die exakten Infos an unsere Nutzer:innen.

**Comment by Lukas2112** [comment]
Okay, that's right, your reasoning is consistent. 

The Federal Ministry of Health could certainly offer something like this with the resources that the Covidbot offers here, couldn't it?

**Comment by errotu** [comment]
It could (and should). In fact, it does provide a service for nearly all messengers which goes in this direction: https://www.zusammengegencorona.de/

**Comment by eknoes** [comment]
Es gibt jetzt eine CSV-Datei, der Inhalt der jeweiligen Zeile wird im täglichen Bericht mitgesendet. Man kann HTML Formatierung nutzen und auch Emojis, nur kein Semikolon! Worte, die in {Klammern} gesetzt werden, werden als Befehl formatiert.
Aus `{Abo}` wird auf Telegram also `/abo` und auf Threema/Signal `"Abo"`.

**Comment by eknoes** [comment]
https://github.com/eknoes/covidbot/blob/main/resources/user-tips.csv
