### ISSUE TITLE
MySQL Connection erneuern statt beenden 

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#68]
Aktuell beendet sich der Bot, wenn bspw. die MySQL Verbindung ausgelaufen ist (nach ca. 8 Stunden ohne Query). Sinnvoll wäre, diese einfach zu erneuern, sodass die Nutzer*in trotzdem eine Antwort und keinen Fehler erhält.

**Comment by eknoes** [comment]
Dazu wäre es vermutlich am einfachsten, in [Bot.py](https://github.com/eknoes/covid-bot/blob/0d57bd22a623f4a6bd158c4bb101711ba6497a58/covidbot/bot.py#L31) eine Funktion zu implementieren, die den UserManager und CovidData austauscht mit "frischen" MySQL Connections und der Input dann im Telegrambot bzw. Textinterface erneut getriggert wird.

**Comment by errotu** [comment]
Ist das noch relevant, @eknoes? Oder haben wir inzwischen so viele Nutzer:innen, dass es schlicht nicht mehr problematisch ist, weil irgendjemand immer in den acht Stunden eine Anfrage stellt?

**Comment by eknoes** [comment]
Das 8h Limit ist kürzer geworden, aktuell passiert das so 2xtäglich, sollten wir also noch ändern.

**Comment by eknoes** [comment]
Scheint nicht mehr relevant
