### ISSUE TITLE
D-64 Branding

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#80]
Der Name sollte überall konsistent sein, ich würde allerdings weiter bei Covidbot bleiben wollen. 

Wir haben unter den Berichten jetzt ein "Ein Service von D64". Man könnte außerdem noch:

- [ ] Graphen schicker machen und ans D64 Layout anpassen

**Comment by errotu** [comment]
Kannst du den Namen bei Telegram zu "Covidbot" anpassen, Sönke? Bei Threema und Signal können wir nichts einstellen, richtig? Wenn der Name angepasst wurde, kann das Issue mE geschlossen werden, weil die Überarbeitung der Grafiken in #96 debattiert wird.

**Comment by eknoes** [comment]
Doch, Namen können wir überall setzen. Ich passe es bei Telegram an.
