### ISSUE TITLE
Add District Abbreviations

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#88]
Add district abbreviations, e.g. license plates.

Data (at least for Germany) could come from here: https://www.govdata.de/suchen/-/details/kfz-kennzeichen-deutschland3785e

**Comment by eknoes** [comment]
Wir könnten auch manuelle Aliase einführen, die wir dann setzen könnten. Das würde sicher einige Probleme lösen, wir könnten das auch gleichzeitig nutzen um OSM Anfragen zu cachen (-> Wenn nur ein Ort das Ergebnis ist, könnten wir diesen dann automatisch als Alias speichern, müssen also in Zukunft nicht mehr OSM abfragen).

**Comment by errotu** [comment]
Manuelle Aliase finde ich super! Bei dem Speichern von eindeutigen OSM-Anfragen bin ich aus Datenschutzgründen skeptisch, weil da ja Leute vielleicht auch ihre persönlichen Adressen eingeben. Will eigentlich keine Datenbank mit solchen Abfragen. Siehst du einen erheblichen Mehrwert, wenn wir OSM-Anfragen reduzieren würden?

**Comment by eknoes** [comment]
Jede OSM Anfrage dauert ca. 2s, gerade bei Tweets und so sehen wir häufig auch zweimal nach mit anderen Filterkriterien -> 4s. Neben der Response Time eigentlich vielleicht den Load auf die OSM Server, die bitten darum zu cachen. Und wenn wir sagen, wir cachen alle Anfragen <10 Zeichen oder sowas?

**Comment by errotu** [comment]
Ja, vielleicht so etwas. Alle Anfragen, die ein eindeutiges Ergebnis liefern, unter 10 Zeichen haben und außerdem wird der Eintrag aus dem Cache entfernt, wenn er seit 14 Tagen nicht mehr abgerufen wurde?

**Comment by eknoes** [comment]
(Inwieweit) müssen wir da unsere Privacy Policy anpassen?

**Comment by errotu** [comment]
Wir sollten es auf jeden Fall aufnehmen, würde ich sagen. Ich schaue sie mir mal in den nächsten Tagen insgesamt ausführlicher an.

**Comment by eknoes** [comment]
Ist jetzt erstmal ohne das Caching implementiert.
