### ISSUE TITLE
Twitter Bot

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#94]
Wir könnten einen Twitter Bot bauen, der einfach jeden Morgen den aktuellen Bericht für Deutschland postet. Dafür sollten wir aber dringend die Grafik verbessern, damit die ein bisschen besser "share-able" wird. Siehe #80. Wir könnten unseren Bot dann auch via DMs anbieten, aber ich würde das eher nachrangig betrachten zu diesem "Ein Tweet am Tag zur aktuellen Lage".

Wir brauchen dafür nur nen [Developer Account](https://developer.twitter.com/), und dann würde das ganz fix gehen. Und einere schönere Grafik!

**Comment by eknoes** [comment]
Siehe #96

**Comment by eknoes** [comment]
Teilweise implementiert mit 1a01c15e86a22d84ccae688f228d14ad96dd04a7, fehlt noch die Reaktion auf Mentions.

**Comment by errotu** [comment]
Vielleicht können wir (falls die Zeichenzahl es noch hergibt) bei den Impfdaten das BMG (@BMG_Bund) direkt verlinken.
