### ISSUE TITLE
(Neue) Grafiken

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#96]
Unsere aktuelle Grafik ist ganz nett, aber ich denke mindestens style mäßig geht da noch was! 

1. Könnten wir zu verschiedenen Themen Grafiken generieren, also auch bspw. zu den Impfungen oder soon den Intensivbetten, siehe #3 
2. Sollten wir die Grafik style-mäßig schicker machen und ein bisschen D64 Branding reinbringen!
3. Sollten wir mehr Informationen in die aktuelle Grafik einbauen

Zu 3. wurde schon mehrmals vorgeschlagen, den Inzidenzwert einzubauen. Ich finde es schwierig, in eine übersichtliche Grafik zwei Arten von "Datentypen" einzubauen, und würde daher vorschlagen eher so einen rolling-average der Neuinfektionen einzubauen - der ist dann vergleichbarer und den könnten wir einfach als Kurve einbauen, ohne eine zweite Y-Achse einzuführen.
Außerdem war mal angedacht, beim aktuellen Infektionswert eine gestrichelte Linie auf der Y-Achse einzuführen, damit es vergleichbarer wird.

**Comment by yorickreum** [comment]
Möchte hier auch anmerken: Wie sinnvoll ist es denn, nur die letzen 21 Tage zu zeigen? So sieht jeder Plot effektiv gleich aus, nur mit anderes skalierten Achsen, dadurch gewinnt man wenig wirklich neue Informationen. Wäre es nicht sinnvoller, einen längeren Zeitraum dazustellen?

**Comment by eknoes** [comment]
Ich bin auch ein Fan von einem längeren Zeitraum. An wie viel denkst du so? Das Problem ist, dass wir aktuell nur die Daten seit dem 30.12.2020 haben, weil wir erst seitdem einmal am Tag die Tagesdaten fetchen. Aber die alten irgendwoher einmal zu importieren würde ja auch gehen.
Andererseits kann man beim aktuellen Zeitraum ganz gut mit den Daten der letzten 3 "Mal" vergleichen, wie stark es fällt / steigt.

**Comment by eknoes** [comment]
Feedback auf Twitter: 

> Denkbar wäre ja, dass ich eine Stadt und Deutschland in einer Grafik bekomme. Man möchte ja sehen, wie gut das eigene Dorf im Verhältnis dasteht. Ich brauch nicht mehrere Städte. Eurem Bot müsste man dann sagen können, welche Stadt in der Grafik stehen soll.

https://twitter.com/sbrinkmann/status/1360221732142014467

**Comment by yorickreum** [comment]
> Ich bin auch ein Fan von einem längeren Zeitraum. An wie viel denkst du so? Das Problem ist, dass wir aktuell nur die Daten seit dem 30.12.2020 haben, weil wir erst seitdem einmal am Tag die Tagesdaten fetchen. Aber die alten irgendwoher einmal zu importieren würde ja auch gehen.
> Andererseits kann man beim aktuellen Zeitraum ganz gut mit den Daten der letzten 3 "Mal" vergleichen, wie stark es fällt / steigt.

Um mir dazu eine fundierte Meinung zu bilden, müsste ich mir die Daten mal für verschiedene Zeiträume anschauen, glaube ich.





> Feedback auf Twitter:
> 
> > Denkbar wäre ja, dass ich eine Stadt und Deutschland in einer Grafik bekomme. Man möchte ja sehen, wie gut das eigene Dorf im Verhältnis dasteht. Ich brauch nicht mehrere Städte. Eurem Bot müsste man dann sagen können, welche Stadt in der Grafik stehen soll.
> 
> https://twitter.com/sbrinkmann/status/1360221732142014467

Klingt gut! Eventuell kann man ja auch Deutschland vs. die selbst ausgewählten Städte in den gleichen Plot packen (zum Beispiel mit verschiedenen Farben). Dann kann man direkt vergleichen.

**Comment by eknoes** [comment]
Prinzipiell kann man die hier alle ansehen: https://corona.rki.de/
Die Daten die wir haben sind Fälle/Tag (Meldung)
