### ISSUE TITLE
Wie erklären wir, warum man DE nicht abonnieren kann?

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#97]
Die Frage kommt häufiger auf. Oder sollen wir es einfach abonnierbar mache, aber ignorieren?

**Comment by errotu** [comment]
Abonnierbar machen wäre langfristig (im Hinblick auf die Internationalisierung) wahrscheinlich einfacher als extra dafür einen Reaktionstext in Richtung "Deutschland wird dir immer geliefert und kann deshalb nicht separat abonniert werden" zu aktivieren.

**Comment by Lukas2112** [comment]
I think that when the Covidbot is internationalised, in addition to the information from the Robert Koch Institute, it will also draw on that from Johns Hopkins University?

**Comment by eknoes** [comment]
Please see for Internationalization #87

**Comment by eknoes** [comment]
Deutschland sollte abonnierbar sein, mit dem Kommando /start sollte man Deutschland automatisch bei Ersteinrichtung abonnieren
