### ISSUE TITLE
Beenden des Bots

### ISSUE THREAD

**Issue by eknoes** [eknoes/covidbot#98]
Ich habe in 1596536a881b7811adba63bb5f0bc58855e3af4a versucht besser darzustellen wie man den Bot beendet. Sollten wir noch Aliase für bspw. `Stop`, `Abmelden`, `Beenden` oder so einführen? Oder dann sowas schreiben wie "Wenn du den Bot abbestellen willst, dan tu X"?

**Comment by errotu** [comment]
Ich wäre für die Einführung der Aliase, dann kann es mE geschlossen werden.
